#!/bin/bash
# Dynamic Environment Setup - Linux Version
# Cross-platform DDS environment configuration

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Dynamic Environment Setup - Linux Version ===${NC}"

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

echo "Script directory: $SCRIPT_DIR"
echo "Project root: $PROJECT_ROOT"

# Portability checks
echo -e "\n${YELLOW}[INFO] Performing portability checks...${NC}"

IDL_DIR="$PROJECT_ROOT/IDL"
DOCS_DIR="$PROJECT_ROOT/docs"
SECURE_DDS_DIR="$PROJECT_ROOT/secure_dds"

if [[ ! -d "$IDL_DIR" ]]; then
    echo -e "${RED}[ERROR] IDL folder not found: $IDL_DIR${NC}"
    exit 1
else
    echo -e "${GREEN}[OK] IDL folder found: $IDL_DIR${NC}"
fi

if [[ ! -d "$DOCS_DIR" ]]; then
    echo -e "${YELLOW}[WARNING] docs folder not found: $DOCS_DIR${NC}"
else
    echo -e "${GREEN}[OK] docs folder found: $DOCS_DIR${NC}"
fi

if [[ ! -d "$SECURE_DDS_DIR" ]]; then
    echo -e "${YELLOW}[WARNING] secure_dds folder not found (certs is deprecated): $SECURE_DDS_DIR${NC}"
else
    echo -e "${GREEN}[OK] secure_dds folder found: $SECURE_DDS_DIR${NC}"
fi

# Run dynamic finder to detect tools
echo -e "\n${YELLOW}[INFO] Running dynamic tool detection...${NC}"
bash "$SCRIPT_DIR/dynamic_finder.sh"

# Load detected environment
ENV_FILE="$SCRIPT_DIR/dds_environment.sh"
if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
    echo -e "${GREEN}[OK] Environment loaded successfully${NC}"
else
    echo -e "${RED}[ERROR] Environment file not found: $ENV_FILE${NC}"
    exit 1
fi

# Verify critical tools
echo -e "\n${YELLOW}[INFO] Verifying tool availability...${NC}"

# Check Python
if [[ -n "$DDS_PYTHON_PATH" && -x "$DDS_PYTHON_PATH" ]]; then
    PYTHON_VERSION=$($DDS_PYTHON_PATH --version 2>&1)
    echo -e "${GREEN}[OK] Python: $PYTHON_VERSION at $DDS_PYTHON_PATH${NC}"
else
    echo -e "${RED}[ERROR] Python not available${NC}"
fi

# Check Java
if [[ -n "$DDS_JAVA_PATH" && -x "$DDS_JAVA_PATH" ]]; then
    JAVA_VERSION=$($DDS_JAVA_PATH -version 2>&1 | head -n 1)
    echo -e "${GREEN}[OK] Java: $JAVA_VERSION at $DDS_JAVA_PATH${NC}"
else
    echo -e "${YELLOW}[WARNING] Java not available${NC}"
fi

# Check CMake
if [[ -n "$DDS_CMAKE_PATH" && -x "$DDS_CMAKE_PATH" ]]; then
    CMAKE_VERSION=$($DDS_CMAKE_PATH --version | head -n 1)
    echo -e "${GREEN}[OK] CMake: $CMAKE_VERSION at $DDS_CMAKE_PATH${NC}"
else
    echo -e "${RED}[ERROR] CMake not available${NC}"
fi

# Check Fast-DDS
if command -v fastddsgen >/dev/null 2>&1; then
    FASTDDS_VERSION=$(fastddsgen -version 2>&1 | head -n 1 || echo "Fast-DDS Generator")
    echo -e "${GREEN}[OK] Fast-DDS: $FASTDDS_VERSION${NC}"
else
    echo -e "${RED}[ERROR] Fast-DDS generator not found${NC}"
    echo "Please install Fast-DDS: https://fast-dds.docs.eprosima.com/"
fi

# Check build tools
if command -v make >/dev/null 2>&1; then
    MAKE_VERSION=$(make --version | head -n 1)
    echo -e "${GREEN}[OK] Make: $MAKE_VERSION${NC}"
elif command -v ninja >/dev/null 2>&1; then
    NINJA_VERSION=$(ninja --version)
    echo -e "${GREEN}[OK] Ninja: $NINJA_VERSION${NC}"
else
    echo -e "${RED}[ERROR] No build system found (make or ninja required)${NC}"
fi

# Check compiler
if command -v g++ >/dev/null 2>&1; then
    GCC_VERSION=$(g++ --version | head -n 1)
    echo -e "${GREEN}[OK] G++: $GCC_VERSION${NC}"
elif command -v clang++ >/dev/null 2>&1; then
    CLANG_VERSION=$(clang++ --version | head -n 1)
    echo -e "${GREEN}[OK] Clang++: $CLANG_VERSION${NC}"
else
    echo -e "${RED}[ERROR] No C++ compiler found (g++ or clang++ required)${NC}"
fi

# Create comprehensive environment script
echo -e "\n${YELLOW}[INFO] Creating comprehensive environment configuration...${NC}"

FULL_ENV_FILE="$PROJECT_ROOT/dds_environment_linux.sh"
cat > "$FULL_ENV_FILE" << EOF
#!/bin/bash
# DDS Environment Configuration - Linux
# Auto-generated by dynamic_environment_setup.sh
# This file is dynamically generated - DO NOT EDIT MANUALLY
# Run: bash scripts/sh/dynamic_environment_setup.sh to regenerate

# Get script directory and project root dynamically
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="\$SCRIPT_DIR"

# Project paths
export DDS_PROJECT_ROOT="\$PROJECT_ROOT"
export DDS_IDL_DIR="\$PROJECT_ROOT/IDL"
export DDS_SCRIPTS_DIR="\$PROJECT_ROOT/scripts/sh"
export DDS_SECURE_DIR="\$PROJECT_ROOT/secure_dds"

# Tool paths (dynamically detected)
export DDS_PYTHON_PATH="\$(command -v python3 2>/dev/null || echo '/usr/bin/python3')"
export DDS_JAVA_PATH="\$(command -v java 2>/dev/null || echo '/usr/bin/java')"
export DDS_CMAKE_PATH="\$(command -v cmake 2>/dev/null || echo '/usr/bin/cmake')"

# Add project scripts to PATH
export PATH="\$DDS_SCRIPTS_DIR:\$PATH"

# Fast-DDS environment
if command -v fastddsgen >/dev/null 2>&1; then
    export FASTDDS_AVAILABLE=1
else
    export FASTDDS_AVAILABLE=0
fi

# Build configuration
export CMAKE_BUILD_TYPE=Release
export DDS_BUILD_PARALLEL_JOBS=\$(nproc)

# Library paths (adjust as needed for your Fast-DDS installation)
if [[ -d "/usr/local/lib" ]]; then
    export LD_LIBRARY_PATH="/usr/local/lib:\$LD_LIBRARY_PATH"
fi

if [[ -d "/opt/fastdds/lib" ]]; then
    export LD_LIBRARY_PATH="/opt/fastdds/lib:\$LD_LIBRARY_PATH"
fi

echo "DDS Linux environment loaded successfully"
echo "Project root: \$DDS_PROJECT_ROOT"
echo "Python: \$DDS_PYTHON_PATH"
echo "CMake: \$DDS_CMAKE_PATH"
EOF

chmod +x "$FULL_ENV_FILE"
echo -e "${GREEN}[OK] Environment configuration saved to: $FULL_ENV_FILE${NC}"

# Create convenience aliases
ALIASES_FILE="$PROJECT_ROOT/dds_aliases_linux.sh"
cat > "$ALIASES_FILE" << EOF
#!/bin/bash
# DDS Convenience Aliases - Linux
# This file is dynamically generated - DO NOT EDIT MANUALLY
# Run: bash scripts/sh/dynamic_environment_setup.sh to regenerate

# Get script directory dynamically
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

# Load environment first
source "\$SCRIPT_DIR/dds_environment_linux.sh"

# Build aliases
alias dds-build='bash \$DDS_SCRIPTS_DIR/sh/IDL_BUILDER.sh'
alias dds-clean='find \$DDS_IDL_DIR -name "*_idl_generated" -type d -exec rm -rf {} + 2>/dev/null || true'
alias dds-env='bash \$DDS_SCRIPTS_DIR/sh/dynamic_environment_setup.sh'

# Security aliases
alias dds-security='cd \$DDS_SCRIPTS_DIR/../py && python3 security.py'
alias dds-patch-idl='cd \$DDS_SCRIPTS_DIR/../py && python3 idl_patcher.py'
alias dds-patch-json='cd \$DDS_SCRIPTS_DIR/../py && python3 json_patcher.py'

# Demo aliases
alias dds-demo='cd \$DDS_PROJECT_ROOT/demo && npm start'

# Quick navigation
alias cd-dds='cd \$DDS_PROJECT_ROOT'
alias cd-idl='cd \$DDS_IDL_DIR'
alias cd-scripts='cd \$DDS_SCRIPTS_DIR'

echo "DDS aliases loaded. Available commands:"
echo "  dds-build     - Build all IDL modules"
echo "  dds-clean     - Clean generated files"
echo "  dds-env       - Refresh environment"
echo "  dds-security  - Apply security patches"
echo "  dds-patch-idl - Patch IDL files"
echo "  dds-patch-json- Patch JSON files"
echo "  dds-demo      - Start demo server"
echo "  cd-dds        - Go to project root"
echo "  cd-idl        - Go to IDL directory"
echo "  cd-scripts    - Go to scripts directory"
EOF

chmod +x "$ALIASES_FILE"
echo -e "${GREEN}[OK] Aliases saved to: $ALIASES_FILE${NC}"

# Final summary
echo -e "\n${BLUE}=== Environment Setup Complete ===${NC}"
echo -e "${GREEN}✓ Environment detection completed${NC}"
echo -e "${GREEN}✓ Configuration files created${NC}"
echo -e "${GREEN}✓ Aliases configured${NC}"

echo -e "\n${YELLOW}To use the DDS environment:${NC}"
echo "  source $FULL_ENV_FILE"
echo "  source $ALIASES_FILE"

echo -e "\n${YELLOW}Or add to your ~/.bashrc:${NC}"
echo "  echo 'source $FULL_ENV_FILE' >> ~/.bashrc"
echo "  echo 'source $ALIASES_FILE' >> ~/.bashrc"

echo -e "\n${GREEN}Setup completed successfully!${NC}"