#!/bin/bash
# DDS Environment Configuration - Linux
# Auto-generated by dynamic_environment_setup.sh
# This file is dynamically generated - DO NOT EDIT MANUALLY
# Run: bash scripts/sh/dynamic_environment_setup.sh to regenerate

# Get script directory and project root dynamically
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

# Project paths
export DDS_PROJECT_ROOT="$PROJECT_ROOT"
export DDS_IDL_DIR="$PROJECT_ROOT/IDL"
export DDS_SCRIPTS_DIR="$PROJECT_ROOT/scripts/sh"
export DDS_SECURE_DIR="$PROJECT_ROOT/secure_dds"

# Tool paths (dynamically detected)
export DDS_PYTHON_PATH="$(command -v python3 2>/dev/null || echo '/usr/bin/python3')"
export DDS_JAVA_PATH="$(command -v java 2>/dev/null || echo '/usr/bin/java')"
export DDS_CMAKE_PATH="$(command -v cmake 2>/dev/null || echo '/usr/bin/cmake')"

# Add project scripts to PATH
export PATH="$DDS_SCRIPTS_DIR:$PATH"

# Fast-DDS environment
if command -v fastddsgen >/dev/null 2>&1; then
    export FASTDDS_AVAILABLE=1
else
    export FASTDDS_AVAILABLE=0
fi

# Build configuration
export CMAKE_BUILD_TYPE=Release
export DDS_BUILD_PARALLEL_JOBS=$(nproc)

# Library paths (adjust as needed for your Fast-DDS installation)
if [[ -d "/usr/local/lib" ]]; then
    export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
fi

if [[ -d "/opt/fastdds/lib" ]]; then
    export LD_LIBRARY_PATH="/opt/fastdds/lib:$LD_LIBRARY_PATH"
fi

echo "DDS Linux environment loaded successfully"
echo "Project root: $DDS_PROJECT_ROOT"
echo "Python: $DDS_PYTHON_PATH"
echo "CMake: $DDS_CMAKE_PATH"
