// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CoreData.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__COREDATA_COREDATA_HPP
#define FAST_DDS_GENERATED__COREDATA_COREDATA_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(COREDATA_SOURCE)
#define COREDATA_DllAPI __declspec( dllexport )
#else
#define COREDATA_DllAPI __declspec( dllimport )
#endif // COREDATA_SOURCE
#else
#define COREDATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define COREDATA_DllAPI
#endif // _WIN32

namespace CoreData {

/*!
 * @brief This class represents the structure FlatCoreData defined by the user in the IDL file.
 * @ingroup CoreData
 */
class FlatCoreData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport FlatCoreData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~FlatCoreData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object FlatCoreData that will be copied.
     */
    eProsima_user_DllExport FlatCoreData(
            const FlatCoreData& x)
    {
                    m_latitude = x.m_latitude;

                    m_longitude = x.m_longitude;

                    m_altitude = x.m_altitude;

                    m_time_seconds = x.m_time_seconds;

                    m_time_nano_seconds = x.m_time_nano_seconds;

                    m_speed_mps = x.m_speed_mps;

                    m_orientation_degrees = x.m_orientation_degrees;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object FlatCoreData that will be copied.
     */
    eProsima_user_DllExport FlatCoreData(
            FlatCoreData&& x) noexcept
    {
        m_latitude = x.m_latitude;
        m_longitude = x.m_longitude;
        m_altitude = x.m_altitude;
        m_time_seconds = x.m_time_seconds;
        m_time_nano_seconds = x.m_time_nano_seconds;
        m_speed_mps = x.m_speed_mps;
        m_orientation_degrees = x.m_orientation_degrees;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object FlatCoreData that will be copied.
     */
    eProsima_user_DllExport FlatCoreData& operator =(
            const FlatCoreData& x)
    {

                    m_latitude = x.m_latitude;

                    m_longitude = x.m_longitude;

                    m_altitude = x.m_altitude;

                    m_time_seconds = x.m_time_seconds;

                    m_time_nano_seconds = x.m_time_nano_seconds;

                    m_speed_mps = x.m_speed_mps;

                    m_orientation_degrees = x.m_orientation_degrees;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object FlatCoreData that will be copied.
     */
    eProsima_user_DllExport FlatCoreData& operator =(
            FlatCoreData&& x) noexcept
    {

        m_latitude = x.m_latitude;
        m_longitude = x.m_longitude;
        m_altitude = x.m_altitude;
        m_time_seconds = x.m_time_seconds;
        m_time_nano_seconds = x.m_time_nano_seconds;
        m_speed_mps = x.m_speed_mps;
        m_orientation_degrees = x.m_orientation_degrees;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x FlatCoreData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const FlatCoreData& x) const
    {
        return (m_latitude == x.m_latitude &&
           m_longitude == x.m_longitude &&
           m_altitude == x.m_altitude &&
           m_time_seconds == x.m_time_seconds &&
           m_time_nano_seconds == x.m_time_nano_seconds &&
           m_speed_mps == x.m_speed_mps &&
           m_orientation_degrees == x.m_orientation_degrees);
    }

    /*!
     * @brief Comparison operator.
     * @param x FlatCoreData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const FlatCoreData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member latitude
     * @param _latitude New value for member latitude
     */
    eProsima_user_DllExport void latitude(
            double _latitude)
    {
        m_latitude = _latitude;
    }

    /*!
     * @brief This function returns the value of member latitude
     * @return Value of member latitude
     */
    eProsima_user_DllExport double latitude() const
    {
        return m_latitude;
    }

    /*!
     * @brief This function returns a reference to member latitude
     * @return Reference to member latitude
     */
    eProsima_user_DllExport double& latitude()
    {
        return m_latitude;
    }


    /*!
     * @brief This function sets a value in member longitude
     * @param _longitude New value for member longitude
     */
    eProsima_user_DllExport void longitude(
            double _longitude)
    {
        m_longitude = _longitude;
    }

    /*!
     * @brief This function returns the value of member longitude
     * @return Value of member longitude
     */
    eProsima_user_DllExport double longitude() const
    {
        return m_longitude;
    }

    /*!
     * @brief This function returns a reference to member longitude
     * @return Reference to member longitude
     */
    eProsima_user_DllExport double& longitude()
    {
        return m_longitude;
    }


    /*!
     * @brief This function sets a value in member altitude
     * @param _altitude New value for member altitude
     */
    eProsima_user_DllExport void altitude(
            float _altitude)
    {
        m_altitude = _altitude;
    }

    /*!
     * @brief This function returns the value of member altitude
     * @return Value of member altitude
     */
    eProsima_user_DllExport float altitude() const
    {
        return m_altitude;
    }

    /*!
     * @brief This function returns a reference to member altitude
     * @return Reference to member altitude
     */
    eProsima_user_DllExport float& altitude()
    {
        return m_altitude;
    }


    /*!
     * @brief This function sets a value in member time_seconds
     * @param _time_seconds New value for member time_seconds
     */
    eProsima_user_DllExport void time_seconds(
            int32_t _time_seconds)
    {
        m_time_seconds = _time_seconds;
    }

    /*!
     * @brief This function returns the value of member time_seconds
     * @return Value of member time_seconds
     */
    eProsima_user_DllExport int32_t time_seconds() const
    {
        return m_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member time_seconds
     * @return Reference to member time_seconds
     */
    eProsima_user_DllExport int32_t& time_seconds()
    {
        return m_time_seconds;
    }


    /*!
     * @brief This function sets a value in member time_nano_seconds
     * @param _time_nano_seconds New value for member time_nano_seconds
     */
    eProsima_user_DllExport void time_nano_seconds(
            uint32_t _time_nano_seconds)
    {
        m_time_nano_seconds = _time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member time_nano_seconds
     * @return Value of member time_nano_seconds
     */
    eProsima_user_DllExport uint32_t time_nano_seconds() const
    {
        return m_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member time_nano_seconds
     * @return Reference to member time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& time_nano_seconds()
    {
        return m_time_nano_seconds;
    }


    /*!
     * @brief This function sets a value in member speed_mps
     * @param _speed_mps New value for member speed_mps
     */
    eProsima_user_DllExport void speed_mps(
            float _speed_mps)
    {
        m_speed_mps = _speed_mps;
    }

    /*!
     * @brief This function returns the value of member speed_mps
     * @return Value of member speed_mps
     */
    eProsima_user_DllExport float speed_mps() const
    {
        return m_speed_mps;
    }

    /*!
     * @brief This function returns a reference to member speed_mps
     * @return Reference to member speed_mps
     */
    eProsima_user_DllExport float& speed_mps()
    {
        return m_speed_mps;
    }


    /*!
     * @brief This function sets a value in member orientation_degrees
     * @param _orientation_degrees New value for member orientation_degrees
     */
    eProsima_user_DllExport void orientation_degrees(
            int16_t _orientation_degrees)
    {
        m_orientation_degrees = _orientation_degrees;
    }

    /*!
     * @brief This function returns the value of member orientation_degrees
     * @return Value of member orientation_degrees
     */
    eProsima_user_DllExport int16_t orientation_degrees() const
    {
        return m_orientation_degrees;
    }

    /*!
     * @brief This function returns a reference to member orientation_degrees
     * @return Reference to member orientation_degrees
     */
    eProsima_user_DllExport int16_t& orientation_degrees()
    {
        return m_orientation_degrees;
    }



private:

    double m_latitude{0.0};
    double m_longitude{0.0};
    float m_altitude{0.0};
    int32_t m_time_seconds{0};
    uint32_t m_time_nano_seconds{0};
    float m_speed_mps{0.0};
    int16_t m_orientation_degrees{0};

};

} // namespace CoreData

#endif // _FAST_DDS_GENERATED_COREDATA_COREDATA_HPP_


