@echo off
REM DDS Environment Configuration - Windows
REM Auto-generated by setup_environment.bat
REM This file is dynamically generated - DO NOT EDIT MANUALLY
REM Run: scripts\bat\setup_environment.bat to regenerate

REM Get script directory and project root dynamically
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
set "PROJECT_ROOT=%SCRIPT_DIR%\.."

REM Project paths
set "DDS_PROJECT_ROOT=%PROJECT_ROOT%"
set "DDS_IDL_DIR=%PROJECT_ROOT%\IDL"
set "DDS_SCRIPTS_DIR=%PROJECT_ROOT%\scripts\bat"
set "DDS_SECURE_DIR=%PROJECT_ROOT%\secure_dds"

REM Tool paths (dynamically detected)
where python >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%i in ('where python') do set "DDS_PYTHON_PATH=%%i"
) else (
    set "DDS_PYTHON_PATH=C:\Python3\python.exe"
)

where java >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%i in ('where java') do set "DDS_JAVA_PATH=%%i"
) else (
    set "DDS_JAVA_PATH=C:\Program Files\Java\bin\java.exe"
)

where cmake >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%i in ('where cmake') do set "DDS_CMAKE_PATH=%%i"
) else (
    set "DDS_CMAKE_PATH=C:\Program Files\CMake\bin\cmake.exe"
)

REM Add project scripts to PATH
set "PATH=%DDS_SCRIPTS_DIR%;%PATH%"

REM Fast-DDS environment
where fastddsgen >nul 2>&1
if not errorlevel 1 (
    set "FASTDDS_AVAILABLE=1"
) else (
    set "FASTDDS_AVAILABLE=0"
)

REM Build configuration
set "CMAKE_BUILD_TYPE=Release"

echo DDS Windows environment loaded successfully
echo Project root: %DDS_PROJECT_ROOT%
echo Python: %DDS_PYTHON_PATH%
echo CMake: %DDS_CMAKE_PATH%

