@echo off
REM Dynamic Environment Setup - Windows Version
REM Cross-platform DDS environment configuration

echo === Dynamic Environment Setup - Windows Version ===

REM Get script directory and project root
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
set "PROJECT_ROOT=%~dp0..\.."

echo Script directory: %SCRIPT_DIR%
echo Project root: %PROJECT_ROOT%

REM Portability checks
echo.
echo [INFO] Performing portability checks...

set "IDL_DIR=%PROJECT_ROOT%\IDL"
set "DOCS_DIR=%PROJECT_ROOT%\docs"
set "SECURE_DDS_DIR=%PROJECT_ROOT%\secure_dds"

if not exist "%IDL_DIR%" (
    echo [ERROR] IDL folder not found: %IDL_DIR%
    exit /b 1
) else (
    echo [OK] IDL folder found: %IDL_DIR%
)

if not exist "%DOCS_DIR%" (
    echo [WARNING] docs folder not found: %DOCS_DIR%
) else (
    echo [OK] docs folder found: %DOCS_DIR%
)

if not exist "%SECURE_DDS_DIR%" (
    echo [WARNING] secure_dds folder not found: %SECURE_DDS_DIR%
) else (
    echo [OK] secure_dds folder found: %SECURE_DDS_DIR%
)

REM Run dynamic finder to detect tools
echo.
echo [INFO] Running dynamic tool detection...
call "%SCRIPT_DIR%\find_tools.bat"

REM Load detected environment
set "ENV_FILE=%SCRIPT_DIR%\export_environment_vars.bat"
if exist "%ENV_FILE%" (
    call "%ENV_FILE%"
    echo [OK] Environment loaded successfully
) else (
    echo [ERROR] Environment file not found: %ENV_FILE%
    echo [INFO] Attempting to create environment file manually...
    REM Fallback: create basic environment file
    (
        echo @echo off
        echo REM DDS Environment Variables - Auto-generated
        echo where python ^>nul 2^>^&1
        echo if not errorlevel 1 ^(
        echo     for /f "delims=" %%%%i in ('where python'^) do set "DDS_PYTHON_PATH=%%%%i"
        echo ^) else ^(
        echo     set "DDS_PYTHON_PATH=C:\Python3\python.exe"
        echo ^)
        echo where java ^>nul 2^>^&1
        echo if not errorlevel 1 ^(
        echo     for /f "delims=" %%%%i in ('where java'^) do set "DDS_JAVA_PATH=%%%%i"
        echo ^) else ^(
        echo     set "DDS_JAVA_PATH=C:\Program Files\Java\bin\java.exe"
        echo ^)
        echo where cmake ^>nul 2^>^&1
        echo if not errorlevel 1 ^(
        echo     for /f "delims=" %%%%i in ('where cmake'^) do set "DDS_CMAKE_PATH=%%%%i"
        echo ^) else ^(
        echo     set "DDS_CMAKE_PATH=C:\Program Files\CMake\bin\cmake.exe"
        echo ^)
    ) > "%ENV_FILE%"
    call "%ENV_FILE%"
    echo [OK] Environment file created and loaded
)

REM Verify critical tools
echo.
echo [INFO] Verifying tool availability...

REM Check Python
where python >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
    echo [OK] Python: %PYTHON_VERSION%
) else (
    echo [ERROR] Python not available
)

REM Check Java
where java >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%i in ('java -version 2^>^&1 ^| findstr /C:"version"') do set JAVA_VERSION=%%i
    echo [OK] Java: %JAVA_VERSION%
) else (
    echo [WARNING] Java not available
)

REM Check CMake
where cmake >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%i in ('cmake --version ^| findstr /C:"version"') do set CMAKE_VERSION=%%i
    echo [OK] CMake: %CMAKE_VERSION%
) else (
    echo [ERROR] CMake not available
)

REM Check Fast-DDS
where fastddsgen >nul 2>&1
if not errorlevel 1 (
    echo [OK] Fast-DDS: Fast-DDS Generator found
) else (
    echo [ERROR] Fast-DDS generator not found
    echo Please install Fast-DDS: https://fast-dds.docs.eprosima.com/
)

REM Check build tools
where msbuild >nul 2>&1
if not errorlevel 1 (
    echo [OK] MSBuild found
) else (
    where ninja >nul 2>&1
    if not errorlevel 1 (
        echo [OK] Ninja found
    ) else (
        echo [ERROR] No build system found (MSBuild or Ninja required)
    )
)

REM Check compiler
where cl >nul 2>&1
if not errorlevel 1 (
    echo [OK] MSVC compiler found
) else (
    where g++ >nul 2>&1
    if not errorlevel 1 (
        echo [OK] G++ found
    ) else (
        echo [ERROR] No C++ compiler found
    )
)

REM Create comprehensive environment script
echo.
echo [INFO] Creating comprehensive environment configuration...

if not exist "%PROJECT_ROOT%\init\bat" mkdir "%PROJECT_ROOT%\init\bat"
set "FULL_ENV_FILE=%PROJECT_ROOT%\init\bat\export_dds_environment.bat"
(
    echo @echo off
    echo REM DDS Environment Configuration - Windows
    echo REM Auto-generated by setup_environment.bat
    echo REM This file is dynamically generated - DO NOT EDIT MANUALLY
    echo REM Run: scripts\bat\setup_environment.bat to regenerate
    echo.
    echo REM Get script directory and project root dynamically
    echo set "SCRIPT_DIR=%%~dp0"
    echo set "SCRIPT_DIR=%%SCRIPT_DIR:~0,-1%%"
    echo set "PROJECT_ROOT=%%SCRIPT_DIR%%\.."
    echo.
    echo REM Project paths
    echo set "DDS_PROJECT_ROOT=%%PROJECT_ROOT%%"
    echo set "DDS_IDL_DIR=%%PROJECT_ROOT%%\IDL"
    echo set "DDS_SCRIPTS_DIR=%%PROJECT_ROOT%%\scripts\bat"
    echo set "DDS_SECURE_DIR=%%PROJECT_ROOT%%\secure_dds"
    echo.
    echo REM Tool paths (dynamically detected)
    echo where python ^>nul 2^>^&1
    echo if not errorlevel 1 ^(
    echo     for /f "delims=" %%%%i in ('where python'^) do set "DDS_PYTHON_PATH=%%%%i"
    echo ^) else ^(
    echo     set "DDS_PYTHON_PATH=C:\Python3\python.exe"
    echo ^)
    echo.
    echo where java ^>nul 2^>^&1
    echo if not errorlevel 1 ^(
    echo     for /f "delims=" %%%%i in ('where java'^) do set "DDS_JAVA_PATH=%%%%i"
    echo ^) else ^(
    echo     set "DDS_JAVA_PATH=C:\Program Files\Java\bin\java.exe"
    echo ^)
    echo.
    echo where cmake ^>nul 2^>^&1
    echo if not errorlevel 1 ^(
    echo     for /f "delims=" %%%%i in ('where cmake'^) do set "DDS_CMAKE_PATH=%%%%i"
    echo ^) else ^(
    echo     set "DDS_CMAKE_PATH=C:\Program Files\CMake\bin\cmake.exe"
    echo ^)
    echo.
    echo REM Add project scripts to PATH
    echo set "PATH=%%DDS_SCRIPTS_DIR%%;%%PATH%%"
    echo.
    echo REM Fast-DDS environment
    echo where fastddsgen ^>nul 2^>^&1
    echo if not errorlevel 1 ^(
    echo     set "FASTDDS_AVAILABLE=1"
    echo ^) else ^(
    echo     set "FASTDDS_AVAILABLE=0"
    echo ^)
    echo.
    echo REM Build configuration
    echo set "CMAKE_BUILD_TYPE=Release"
    echo.
    echo echo DDS Windows environment loaded successfully
    echo echo Project root: %%DDS_PROJECT_ROOT%%
    echo echo Python: %%DDS_PYTHON_PATH%%
    echo echo CMake: %%DDS_CMAKE_PATH%%
) > "%FULL_ENV_FILE%"

echo [OK] Environment configuration saved to: %FULL_ENV_FILE%

REM Final summary
echo.
echo === Environment Setup Complete ===
echo ✓ Environment detection completed
echo ✓ Configuration files created
echo.
echo To use the DDS environment:
echo   call %FULL_ENV_FILE%
echo.
echo Setup completed successfully!
pause
exit /b 0

