// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CoreData3PublisherApp.cxx
 * This file contains the implementation of the publisher functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "CoreData3PublisherApp.hpp"

#include <condition_variable>
#include <csignal>
#include <stdexcept>
#include <thread>

#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/publisher/qos/DataWriterQos.hpp>
#include <fastdds/dds/publisher/qos/PublisherQos.hpp>

#include "CoreData3PubSubTypes.hpp"
#include <filesystem>
#include <unistd.h>
#include <cstring>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
#include <vector>

using namespace eprosima::fastdds::dds;

CoreData3PublisherApp::CoreData3PublisherApp(
        const int& domain_id)
    : factory_(nullptr)
    , participant_(nullptr)
    , publisher_(nullptr)
    , topic_(nullptr)
    , writer_(nullptr)
    , type_(new CoreData::FlatCoreDataPubSubType())
    , matched_(0)
    , samples_sent_(0)
    , stop_(false)
{
    //
    // Resolve DDS root directory dynamically (portable across PCs)
    auto resolve_dds_root = []() -> std::filesystem::path {
        if (const char* env_root = std::getenv("DDS_ROOT")) {
            std::filesystem::path p(env_root);
            if (std::filesystem::exists(p)) return p;
        }
        // Walk upwards from current directory to find repo root (has secure_dds and IDL)
        std::filesystem::path cur = std::filesystem::current_path();
        for (int i = 0; i < 6 && !cur.empty(); ++i) {
            if (std::filesystem::exists(cur / "secure_dds") && std::filesystem::exists(cur / "IDL")) {
                return cur;
            }
            cur = cur.parent_path();
        }
        return std::filesystem::current_path();
    };
    
    // Detect hostname dynamically (portable across PCs)
    char hostname[256] = {0};
    if (gethostname(hostname, sizeof(hostname) - 1) != 0) {
        std::strcpy(hostname, "UNKNOWN_HOST");
    }
    std::string participant_dir = std::string(hostname);
    
    const std::filesystem::path dds_root = resolve_dds_root();

    // Create the participant
    DomainParticipantQos pqos = PARTICIPANT_QOS_DEFAULT;
    // DDS Security Configuration - Authentication + Encryption Only
    pqos.properties().properties().emplace_back("dds.sec.auth.plugin", "builtin.PKI-DH");
    // Access Control disabled to avoid permissions issues
    pqos.properties().properties().emplace_back("dds.sec.crypto.plugin", "builtin.AES-GCM-GMAC");
    
    // Certificate and Key Paths (dynamic, portable across PCs)
    const std::string uri_prefix = "file://";
    const std::filesystem::path ca_path = dds_root / "secure_dds/CA/mainca_cert.pem";
    const std::filesystem::path cert_path = dds_root / "secure_dds/participants" / participant_dir / (participant_dir + "_cert.pem");
    const std::filesystem::path key_path = dds_root / "secure_dds/participants" / participant_dir / (participant_dir + "_key.pem");
    
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.identity_ca", uri_prefix + ca_path.string());
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.identity_certificate", uri_prefix + cert_path.string());
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.private_key", uri_prefix + key_path.string());
    
    // Access Control disabled - no governance/permissions needed
    pqos.name("CoreData::FlatCoreData_pub_participant");
    factory_ = DomainParticipantFactory::get_shared_instance();
    participant_ = factory_->create_participant(domain_id, pqos, nullptr, StatusMask::none());
    if (participant_ == nullptr)
    {
        throw std::runtime_error("CoreData::FlatCoreData Participant initialization failed");
    }

    // Register the type
    type_.register_type(participant_);

    // Create the publisher
    PublisherQos pub_qos = PUBLISHER_QOS_DEFAULT;
    participant_->get_default_publisher_qos(pub_qos);
    publisher_ = participant_->create_publisher(pub_qos, nullptr, StatusMask::none());
    if (publisher_ == nullptr)
    {
        throw std::runtime_error("CoreData::FlatCoreData Publisher initialization failed");
    }

    // Create the topic
    TopicQos topic_qos = TOPIC_QOS_DEFAULT;
    participant_->get_default_topic_qos(topic_qos);
    topic_ = participant_->create_topic("CoreData3Topic", type_.get_type_name(), topic_qos);
    if (topic_ == nullptr)
    {
        throw std::runtime_error("CoreData::FlatCoreData Topic initialization failed");
    }

    // Create the data writer
    DataWriterQos writer_qos = DATAWRITER_QOS_DEFAULT;
    // Payload Encryption Configuration
    writer_qos.properties().properties().emplace_back("rtps.payload_protection", "ENCRYPT");
    publisher_->get_default_datawriter_qos(writer_qos);
    writer_qos.reliability().kind = ReliabilityQosPolicyKind::RELIABLE_RELIABILITY_QOS;
    writer_qos.durability().kind = DurabilityQosPolicyKind::TRANSIENT_LOCAL_DURABILITY_QOS;
    writer_qos.history().kind = HistoryQosPolicyKind::KEEP_ALL_HISTORY_QOS;
    writer_ = publisher_->create_datawriter(topic_, writer_qos, this, StatusMask::all());
    if (writer_ == nullptr)
    {
        throw std::runtime_error("CoreData::FlatCoreData DataWriter initialization failed");
    }
}

CoreData3PublisherApp::~CoreData3PublisherApp()
{
    if (nullptr != participant_)
    {
        // Delete DDS entities contained within the DomainParticipant
        participant_->delete_contained_entities();

        // Delete DomainParticipant
        factory_->delete_participant(participant_);
    }
}

void CoreData3PublisherApp::on_publication_matched(
        DataWriter* /*writer*/,
        const PublicationMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            matched_ = info.current_count;
        }
        std::cout << "CoreData::FlatCoreData Publisher matched." << std::endl;
        cv_.notify_one();
    }
    else if (info.current_count_change == -1)
    {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            matched_ = info.current_count;
        }
        std::cout << "CoreData::FlatCoreData Publisher unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
                  << " is not a valid value for PublicationMatchedStatus current count change" << std::endl;
    }
}

void CoreData3PublisherApp::run()
{
    while (!is_stopped())
    {
        if (publish())
        {
            std::cout << "Sample '" << std::to_string(++samples_sent_) << "' SENT" << std::endl;
        }
        // Wait for period or stop event
        std::unique_lock<std::mutex> period_lock(mutex_);
        cv_.wait_for(period_lock, std::chrono::milliseconds(period_ms_), [this]()
                {
                    return is_stopped();
                });
    }
}


bool CoreData3PublisherApp::publish()
{
    bool ret = false;
    // Wait for the data endpoints discovery
    std::unique_lock<std::mutex> matched_lock(mutex_);
    cv_.wait(matched_lock, [&]()
            {
                // at least one has been discovered
                return ((matched_ > 0) || is_stopped());
            });

    if (!is_stopped())
    {
        /* Initialize your structure here */
        CoreData::FlatCoreData sample_;
        // --- BEGIN AUTOGENERATED IDL PATCH (v9) - JSON ENHANCED ---
        // JSON data reading setup
        static std::vector<nlohmann::json> json_data;
        static size_t current_index = 0;
        static bool json_loaded = false;
        
        if (!json_loaded) {
            // Try multiple possible paths for the JSON file
            std::vector<std::string> possible_paths = {
                "scenarios/CoreData3.json",
                "../../scenarios/CoreData3.json",
                "../../../scenarios/CoreData3.json"
            };
            
            bool file_found = false;
            for (const auto& path : possible_paths) {
                std::ifstream json_file(path);
                if (json_file.is_open()) {
                    file_found = true;
                    nlohmann::json j;
                    json_file >> j;
                    if (j.is_array()) {
                        json_data = j.get<std::vector<nlohmann::json>>();
                    } else {
                        json_data.push_back(j);
                    }
                    json_loaded = true;
                    std::cout << "Loaded " << json_data.size() << " entries from " << path << std::endl;
                    break;
                }
            }
            
            if (!file_found) {
                std::cerr << "Warning: Could not find CoreData3.json in any expected location, using default values" << std::endl;
            }
        }
        
        // Use JSON data if available, otherwise use defaults
        if (!json_data.empty()) {
            const auto& current_data = json_data[current_index % json_data.size()];
            
            // Set values from JSON data
            if (current_data.contains("latitude")) {
                sample_.latitude(current_data["latitude"].get<float>());
            } else {
                sample_.latitude(37.7749);
            }
            if (current_data.contains("longitude")) {
                sample_.longitude(current_data["longitude"].get<float>());
            } else {
                sample_.longitude(-122.4194);
            }
            if (current_data.contains("altitude")) {
                sample_.altitude(current_data["altitude"].get<float>());
            } else {
                sample_.altitude(100.0f);
            }
            if (current_data.contains("time_seconds")) {
                sample_.time_seconds(current_data["time_seconds"].get<long>());
            } else {
                sample_.time_seconds(1678886400L);
            }
            if (current_data.contains("time_nano_seconds")) {
                sample_.time_nano_seconds(current_data["time_nano_seconds"].get<long>());
            } else {
                sample_.time_nano_seconds(1678886400L);
            }
            if (current_data.contains("speed_mps")) {
                sample_.speed_mps(current_data["speed_mps"].get<float>());
            } else {
                sample_.speed_mps(15.5f);
            }
            if (current_data.contains("orientation_degrees")) {
                sample_.orientation_degrees(current_data["orientation_degrees"].get<int>());
            } else {
                sample_.orientation_degrees(180);
            }
            
            // Move to next data entry for next publish
            current_index++;
        } else {
            // Fallback to original hardcoded values
            sample_.latitude(37.7749);
            sample_.longitude(-122.4194);
            sample_.altitude(100.0f);
            sample_.time_seconds(1678886400L);
            sample_.time_nano_seconds(1678886400L);
            sample_.speed_mps(15.5f);
            sample_.orientation_degrees(180);
        }
        // --- END AUTOGENERATED IDL PATCH (v9) - JSON ENHANCED ---

        ret = (RETCODE_OK == writer_->write(&sample_));
    }
    return ret;
}

bool CoreData3PublisherApp::is_stopped()
{
    return stop_.load();
}

void CoreData3PublisherApp::stop()
{
    stop_.store(true);
    cv_.notify_one();
}