// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CoreData3SubscriberApp.cxx
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "CoreData3SubscriberApp.hpp"

#include <condition_variable>
#include <stdexcept>

#include <fastdds/dds/core/status/SubscriptionMatchedStatus.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>
#include <fastdds/dds/subscriber/qos/SubscriberQos.hpp>
#include <fastdds/dds/subscriber/SampleInfo.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>

#include "CoreData3PubSubTypes.hpp"
#include <filesystem>
#include <unistd.h>
#include <cstring>

using namespace eprosima::fastdds::dds;

CoreData3SubscriberApp::CoreData3SubscriberApp(
        const int& domain_id)
    : factory_(nullptr)
    , participant_(nullptr)
    , subscriber_(nullptr)
    , topic_(nullptr)
    , reader_(nullptr)
    , type_(new CoreData::FlatCoreDataPubSubType())
    , samples_received_(0)
    , stop_(false)
{
    // Resolve DDS root directory dynamically (portable across PCs)
    auto resolve_dds_root = []() -> std::filesystem::path {
        if (const char* env_root = std::getenv("DDS_ROOT")) {
            std::filesystem::path p(env_root);
            if (std::filesystem::exists(p)) return p;
        }
        // Walk upwards from current directory to find repo root (has secure_dds and IDL)
        std::filesystem::path cur = std::filesystem::current_path();
        for (int i = 0; i < 6 && !cur.empty(); ++i) {
            if (std::filesystem::exists(cur / "secure_dds") && std::filesystem::exists(cur / "IDL")) {
                return cur;
            }
            cur = cur.parent_path();
        }
        return std::filesystem::current_path();
    };
    
    // Detect hostname dynamically (portable across PCs)
    char hostname[256] = {0};
    if (gethostname(hostname, sizeof(hostname) - 1) != 0) {
        std::strcpy(hostname, "UNKNOWN_HOST");
    }
    std::string participant_dir = std::string(hostname);
    
    const std::filesystem::path dds_root = resolve_dds_root();

    // Create the participant
    DomainParticipantQos pqos = PARTICIPANT_QOS_DEFAULT;
    // DDS Security Configuration - Authentication + Encryption Only
    pqos.properties().properties().emplace_back("dds.sec.auth.plugin", "builtin.PKI-DH");
    // Access Control disabled to avoid permissions issues
    pqos.properties().properties().emplace_back("dds.sec.crypto.plugin", "builtin.AES-GCM-GMAC");
    
    // Certificate and Key Paths (dynamic, portable across PCs)
    const std::string uri_prefix = "file://";
    const std::filesystem::path ca_path = dds_root / "secure_dds/CA/mainca_cert.pem";
    const std::filesystem::path cert_path = dds_root / "secure_dds/participants" / participant_dir / (participant_dir + "_cert.pem");
    const std::filesystem::path key_path = dds_root / "secure_dds/participants" / participant_dir / (participant_dir + "_key.pem");
    
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.identity_ca", uri_prefix + ca_path.string());
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.identity_certificate", uri_prefix + cert_path.string());
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.private_key", uri_prefix + key_path.string());
    
    // Access Control disabled - no governance/permissions needed
    pqos.name("CoreData::FlatCoreData_sub_participant");
    factory_ = DomainParticipantFactory::get_shared_instance();
    participant_ = factory_->create_participant(domain_id, pqos, nullptr, StatusMask::none());
    if (participant_ == nullptr)
    {
        throw std::runtime_error("CoreData::FlatCoreData Participant initialization failed");
    }

    // Register the type
    type_.register_type(participant_);

    // Create the subscriber
    SubscriberQos sub_qos = SUBSCRIBER_QOS_DEFAULT;
    participant_->get_default_subscriber_qos(sub_qos);
    subscriber_ = participant_->create_subscriber(sub_qos, nullptr, StatusMask::none());
    if (subscriber_ == nullptr)
    {
        throw std::runtime_error("CoreData::FlatCoreData Subscriber initialization failed");
    }

    // Create the topic
    TopicQos topic_qos = TOPIC_QOS_DEFAULT;
    participant_->get_default_topic_qos(topic_qos);
    topic_ = participant_->create_topic("CoreData3Topic", type_.get_type_name(), topic_qos);
    if (topic_ == nullptr)
    {
        throw std::runtime_error("CoreData::FlatCoreData Topic initialization failed");
    }

    // Create the reader
    DataReaderQos reader_qos = DATAREADER_QOS_DEFAULT;
    // Payload Encryption Configuration
    reader_qos.properties().properties().emplace_back("rtps.payload_protection", "ENCRYPT");
    subscriber_->get_default_datareader_qos(reader_qos);
    reader_qos.reliability().kind = ReliabilityQosPolicyKind::RELIABLE_RELIABILITY_QOS;
    reader_qos.durability().kind = DurabilityQosPolicyKind::TRANSIENT_LOCAL_DURABILITY_QOS;
    reader_qos.history().kind = HistoryQosPolicyKind::KEEP_ALL_HISTORY_QOS;
    reader_ = subscriber_->create_datareader(topic_, reader_qos, this, StatusMask::all());
    if (reader_ == nullptr)
    {
        throw std::runtime_error("CoreData::FlatCoreData DataReader initialization failed");
    }
}

CoreData3SubscriberApp::~CoreData3SubscriberApp()
{
    if (nullptr != participant_)
    {
        // Delete DDS entities contained within the DomainParticipant
        participant_->delete_contained_entities();

        // Delete DomainParticipant
        factory_->delete_participant(participant_);
    }
}

void CoreData3SubscriberApp::on_subscription_matched(
        DataReader* /*reader*/,
        const SubscriptionMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        std::cout << "CoreData::FlatCoreData Subscriber matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        std::cout << "CoreData::FlatCoreData Subscriber unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
                  << " is not a valid value for SubscriptionMatchedStatus current count change" << std::endl;
    }
}

void CoreData3SubscriberApp::on_data_available(
        DataReader* reader)
{
    CoreData::FlatCoreData sample_;
    SampleInfo info;
    while ((!is_stopped()) && (RETCODE_OK == reader->take_next_sample(&sample_, &info)))
    {
        if ((info.instance_state == ALIVE_INSTANCE_STATE) && info.valid_data)
        {
            std::cout << "Sample '" << std::to_string(++samples_received_) << "' RECEIVED" << std::endl;
            std::cout << " - {";
            std::cout << "latitude: " << sample_.latitude() << ", ";
            std::cout << "longitude: " << sample_.longitude() << ", ";
            std::cout << "altitude: " << sample_.altitude() << ", ";
            std::cout << "time_seconds: " << sample_.time_seconds() << ", ";
            std::cout << "time_nano_seconds: " << sample_.time_nano_seconds() << ", ";
            std::cout << "speed_mps: " << sample_.speed_mps() << ", ";
            std::cout << "orientation_degrees: " << sample_.orientation_degrees() << "";
            std::cout << "}" << std::endl;
        }
    }
}

void CoreData3SubscriberApp::run()
{
    std::unique_lock<std::mutex> lck(terminate_cv_mtx_);
    terminate_cv_.wait(lck, [this]
            {
                return is_stopped();
            });
}

bool CoreData3SubscriberApp::is_stopped()
{
    return stop_.load();
}

void CoreData3SubscriberApp::stop()
{
    stop_.store(true);
    terminate_cv_.notify_all();
}