// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CoreData2TypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "CoreData2TypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "CoreData2.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace CoreData {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_FlatCoreData_type_identifier(
        TypeIdentifierPair& type_ids_FlatCoreData)
{

    ReturnCode_t return_code_FlatCoreData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_FlatCoreData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "CoreData::FlatCoreData", type_ids_FlatCoreData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_FlatCoreData)
    {
        StructTypeFlag struct_flags_FlatCoreData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_FlatCoreData = "CoreData::FlatCoreData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_FlatCoreData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_FlatCoreData;
        CompleteTypeDetail detail_FlatCoreData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_FlatCoreData, ann_custom_FlatCoreData, type_name_FlatCoreData.to_string());
        CompleteStructHeader header_FlatCoreData;
        header_FlatCoreData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_FlatCoreData);
        CompleteStructMemberSeq member_seq_FlatCoreData;
        {
            TypeIdentifierPair type_ids_latitude;
            ReturnCode_t return_code_latitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_latitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_latitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_latitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "latitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_latitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_latitude = 0x00000000;
            bool common_latitude_ec {false};
            CommonStructMember common_latitude {TypeObjectUtils::build_common_struct_member(member_id_latitude, member_flags_latitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_latitude, common_latitude_ec))};
            if (!common_latitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure latitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_latitude = "latitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_latitude;
            ann_custom_FlatCoreData.reset();
            CompleteMemberDetail detail_latitude = TypeObjectUtils::build_complete_member_detail(name_latitude, member_ann_builtin_latitude, ann_custom_FlatCoreData);
            CompleteStructMember member_latitude = TypeObjectUtils::build_complete_struct_member(common_latitude, detail_latitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatCoreData, member_latitude);
        }
        {
            TypeIdentifierPair type_ids_longitude;
            ReturnCode_t return_code_longitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_longitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_longitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_longitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "longitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_longitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_longitude = 0x00000001;
            bool common_longitude_ec {false};
            CommonStructMember common_longitude {TypeObjectUtils::build_common_struct_member(member_id_longitude, member_flags_longitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_longitude, common_longitude_ec))};
            if (!common_longitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure longitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_longitude = "longitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_longitude;
            ann_custom_FlatCoreData.reset();
            CompleteMemberDetail detail_longitude = TypeObjectUtils::build_complete_member_detail(name_longitude, member_ann_builtin_longitude, ann_custom_FlatCoreData);
            CompleteStructMember member_longitude = TypeObjectUtils::build_complete_struct_member(common_longitude, detail_longitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatCoreData, member_longitude);
        }
        {
            TypeIdentifierPair type_ids_altitude;
            ReturnCode_t return_code_altitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_altitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_altitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_altitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "altitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_altitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_altitude = 0x00000002;
            bool common_altitude_ec {false};
            CommonStructMember common_altitude {TypeObjectUtils::build_common_struct_member(member_id_altitude, member_flags_altitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_altitude, common_altitude_ec))};
            if (!common_altitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure altitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_altitude = "altitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_altitude;
            ann_custom_FlatCoreData.reset();
            CompleteMemberDetail detail_altitude = TypeObjectUtils::build_complete_member_detail(name_altitude, member_ann_builtin_altitude, ann_custom_FlatCoreData);
            CompleteStructMember member_altitude = TypeObjectUtils::build_complete_struct_member(common_altitude, detail_altitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatCoreData, member_altitude);
        }
        {
            TypeIdentifierPair type_ids_time_seconds;
            ReturnCode_t return_code_time_seconds {eprosima::fastdds::dds::RETCODE_OK};
            return_code_time_seconds =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_time_seconds);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_time_seconds)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "time_seconds Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_time_seconds = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_time_seconds = 0x00000003;
            bool common_time_seconds_ec {false};
            CommonStructMember common_time_seconds {TypeObjectUtils::build_common_struct_member(member_id_time_seconds, member_flags_time_seconds, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_time_seconds, common_time_seconds_ec))};
            if (!common_time_seconds_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure time_seconds member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_time_seconds = "time_seconds";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_time_seconds;
            ann_custom_FlatCoreData.reset();
            CompleteMemberDetail detail_time_seconds = TypeObjectUtils::build_complete_member_detail(name_time_seconds, member_ann_builtin_time_seconds, ann_custom_FlatCoreData);
            CompleteStructMember member_time_seconds = TypeObjectUtils::build_complete_struct_member(common_time_seconds, detail_time_seconds);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatCoreData, member_time_seconds);
        }
        {
            TypeIdentifierPair type_ids_time_nano_seconds;
            ReturnCode_t return_code_time_nano_seconds {eprosima::fastdds::dds::RETCODE_OK};
            return_code_time_nano_seconds =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_time_nano_seconds);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_time_nano_seconds)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "time_nano_seconds Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_time_nano_seconds = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_time_nano_seconds = 0x00000004;
            bool common_time_nano_seconds_ec {false};
            CommonStructMember common_time_nano_seconds {TypeObjectUtils::build_common_struct_member(member_id_time_nano_seconds, member_flags_time_nano_seconds, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_time_nano_seconds, common_time_nano_seconds_ec))};
            if (!common_time_nano_seconds_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure time_nano_seconds member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_time_nano_seconds = "time_nano_seconds";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_time_nano_seconds;
            ann_custom_FlatCoreData.reset();
            CompleteMemberDetail detail_time_nano_seconds = TypeObjectUtils::build_complete_member_detail(name_time_nano_seconds, member_ann_builtin_time_nano_seconds, ann_custom_FlatCoreData);
            CompleteStructMember member_time_nano_seconds = TypeObjectUtils::build_complete_struct_member(common_time_nano_seconds, detail_time_nano_seconds);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatCoreData, member_time_nano_seconds);
        }
        {
            TypeIdentifierPair type_ids_speed_mps;
            ReturnCode_t return_code_speed_mps {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed_mps =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_speed_mps);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed_mps)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "speed_mps Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_speed_mps = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed_mps = 0x00000005;
            bool common_speed_mps_ec {false};
            CommonStructMember common_speed_mps {TypeObjectUtils::build_common_struct_member(member_id_speed_mps, member_flags_speed_mps, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed_mps, common_speed_mps_ec))};
            if (!common_speed_mps_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed_mps member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed_mps = "speed_mps";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed_mps;
            ann_custom_FlatCoreData.reset();
            CompleteMemberDetail detail_speed_mps = TypeObjectUtils::build_complete_member_detail(name_speed_mps, member_ann_builtin_speed_mps, ann_custom_FlatCoreData);
            CompleteStructMember member_speed_mps = TypeObjectUtils::build_complete_struct_member(common_speed_mps, detail_speed_mps);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatCoreData, member_speed_mps);
        }
        {
            TypeIdentifierPair type_ids_orientation_degrees;
            ReturnCode_t return_code_orientation_degrees {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_degrees =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int16_t", type_ids_orientation_degrees);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_degrees)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_degrees Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_degrees = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_degrees = 0x00000006;
            bool common_orientation_degrees_ec {false};
            CommonStructMember common_orientation_degrees {TypeObjectUtils::build_common_struct_member(member_id_orientation_degrees, member_flags_orientation_degrees, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_degrees, common_orientation_degrees_ec))};
            if (!common_orientation_degrees_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_degrees member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_degrees = "orientation_degrees";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_degrees;
            ann_custom_FlatCoreData.reset();
            CompleteMemberDetail detail_orientation_degrees = TypeObjectUtils::build_complete_member_detail(name_orientation_degrees, member_ann_builtin_orientation_degrees, ann_custom_FlatCoreData);
            CompleteStructMember member_orientation_degrees = TypeObjectUtils::build_complete_struct_member(common_orientation_degrees, detail_orientation_degrees);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatCoreData, member_orientation_degrees);
        }
        CompleteStructType struct_type_FlatCoreData = TypeObjectUtils::build_complete_struct_type(struct_flags_FlatCoreData, header_FlatCoreData, member_seq_FlatCoreData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_FlatCoreData, type_name_FlatCoreData.to_string(), type_ids_FlatCoreData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "CoreData::FlatCoreData already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace CoreData

