// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Messaging.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__MESSAGİNG_MESSAGİNG_HPP
#define FAST_DDS_GENERATED__MESSAGİNG_MESSAGİNG_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MESSAGİNG_SOURCE)
#define MESSAGİNG_DllAPI __declspec( dllexport )
#else
#define MESSAGİNG_DllAPI __declspec( dllimport )
#endif // MESSAGİNG_SOURCE
#else
#define MESSAGİNG_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MESSAGİNG_DllAPI
#endif // _WIN32

namespace Messaging {

/*!
 * @brief This class represents the structure FlatMessagingPacket defined by the user in the IDL file.
 * @ingroup Messaging
 */
class FlatMessagingPacket
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport FlatMessagingPacket()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~FlatMessagingPacket()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object FlatMessagingPacket that will be copied.
     */
    eProsima_user_DllExport FlatMessagingPacket(
            const FlatMessagingPacket& x)
    {
                    m_message_type = x.m_message_type;

                    m_sr_header_sender_id = x.m_sr_header_sender_id;

                    m_sr_header_time_seconds = x.m_sr_header_time_seconds;

                    m_sr_header_time_nano_seconds = x.m_sr_header_time_nano_seconds;

                    m_sr_location_latitude = x.m_sr_location_latitude;

                    m_sr_location_longitude = x.m_sr_location_longitude;

                    m_sr_location_altitude = x.m_sr_location_altitude;

                    m_sr_location_time_seconds = x.m_sr_location_time_seconds;

                    m_sr_location_time_nano_seconds = x.m_sr_location_time_nano_seconds;

                    m_sr_location_speed_mps = x.m_sr_location_speed_mps;

                    m_sr_location_orientation_degrees = x.m_sr_location_orientation_degrees;

                    m_sr_status_task_status = x.m_sr_status_task_status;

                    m_sr_status_battery_percentage = x.m_sr_status_battery_percentage;

                    m_sr_status_signal_strength_dbm = x.m_sr_status_signal_strength_dbm;

                    m_sr_status_system_error = x.m_sr_status_system_error;

                    m_cd_header_sender_id = x.m_cd_header_sender_id;

                    m_cd_header_time_seconds = x.m_cd_header_time_seconds;

                    m_cd_header_time_nano_seconds = x.m_cd_header_time_nano_seconds;

                    m_cd_detection_target_ID = x.m_cd_detection_target_ID;

                    m_cd_detection_target_type = x.m_cd_detection_target_type;

                    m_cd_detection_loc_latitude = x.m_cd_detection_loc_latitude;

                    m_cd_detection_loc_longitude = x.m_cd_detection_loc_longitude;

                    m_cd_detection_loc_altitude = x.m_cd_detection_loc_altitude;

                    m_cd_detection_loc_time_seconds = x.m_cd_detection_loc_time_seconds;

                    m_cd_detection_loc_time_nano_seconds = x.m_cd_detection_loc_time_nano_seconds;

                    m_cd_detection_loc_speed_mps = x.m_cd_detection_loc_speed_mps;

                    m_cd_detection_loc_orientation_degrees = x.m_cd_detection_loc_orientation_degrees;

                    m_cd_detection_confidence_level = x.m_cd_detection_confidence_level;

                    m_cd_detection_description = x.m_cd_detection_description;

                    m_cd_detection_raw_data_link = x.m_cd_detection_raw_data_link;

                    m_tc_header_sender_id = x.m_tc_header_sender_id;

                    m_tc_header_time_seconds = x.m_tc_header_time_seconds;

                    m_tc_header_time_nano_seconds = x.m_tc_header_time_nano_seconds;

                    m_tc_receiver_id = x.m_tc_receiver_id;

                    m_tc_assignment_command = x.m_tc_assignment_command;

                    m_tc_assignment_loc_latitude = x.m_tc_assignment_loc_latitude;

                    m_tc_assignment_loc_longitude = x.m_tc_assignment_loc_longitude;

                    m_tc_assignment_loc_altitude = x.m_tc_assignment_loc_altitude;

                    m_tc_assignment_loc_time_seconds = x.m_tc_assignment_loc_time_seconds;

                    m_tc_assignment_loc_time_nano_seconds = x.m_tc_assignment_loc_time_nano_seconds;

                    m_tc_assignment_loc_speed_mps = x.m_tc_assignment_loc_speed_mps;

                    m_tc_assignment_loc_orientation_degrees = x.m_tc_assignment_loc_orientation_degrees;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object FlatMessagingPacket that will be copied.
     */
    eProsima_user_DllExport FlatMessagingPacket(
            FlatMessagingPacket&& x) noexcept
    {
        m_message_type = x.m_message_type;
        m_sr_header_sender_id = std::move(x.m_sr_header_sender_id);
        m_sr_header_time_seconds = x.m_sr_header_time_seconds;
        m_sr_header_time_nano_seconds = x.m_sr_header_time_nano_seconds;
        m_sr_location_latitude = x.m_sr_location_latitude;
        m_sr_location_longitude = x.m_sr_location_longitude;
        m_sr_location_altitude = x.m_sr_location_altitude;
        m_sr_location_time_seconds = x.m_sr_location_time_seconds;
        m_sr_location_time_nano_seconds = x.m_sr_location_time_nano_seconds;
        m_sr_location_speed_mps = x.m_sr_location_speed_mps;
        m_sr_location_orientation_degrees = x.m_sr_location_orientation_degrees;
        m_sr_status_task_status = x.m_sr_status_task_status;
        m_sr_status_battery_percentage = x.m_sr_status_battery_percentage;
        m_sr_status_signal_strength_dbm = x.m_sr_status_signal_strength_dbm;
        m_sr_status_system_error = x.m_sr_status_system_error;
        m_cd_header_sender_id = std::move(x.m_cd_header_sender_id);
        m_cd_header_time_seconds = x.m_cd_header_time_seconds;
        m_cd_header_time_nano_seconds = x.m_cd_header_time_nano_seconds;
        m_cd_detection_target_ID = std::move(x.m_cd_detection_target_ID);
        m_cd_detection_target_type = x.m_cd_detection_target_type;
        m_cd_detection_loc_latitude = x.m_cd_detection_loc_latitude;
        m_cd_detection_loc_longitude = x.m_cd_detection_loc_longitude;
        m_cd_detection_loc_altitude = x.m_cd_detection_loc_altitude;
        m_cd_detection_loc_time_seconds = x.m_cd_detection_loc_time_seconds;
        m_cd_detection_loc_time_nano_seconds = x.m_cd_detection_loc_time_nano_seconds;
        m_cd_detection_loc_speed_mps = x.m_cd_detection_loc_speed_mps;
        m_cd_detection_loc_orientation_degrees = x.m_cd_detection_loc_orientation_degrees;
        m_cd_detection_confidence_level = x.m_cd_detection_confidence_level;
        m_cd_detection_description = std::move(x.m_cd_detection_description);
        m_cd_detection_raw_data_link = std::move(x.m_cd_detection_raw_data_link);
        m_tc_header_sender_id = std::move(x.m_tc_header_sender_id);
        m_tc_header_time_seconds = x.m_tc_header_time_seconds;
        m_tc_header_time_nano_seconds = x.m_tc_header_time_nano_seconds;
        m_tc_receiver_id = std::move(x.m_tc_receiver_id);
        m_tc_assignment_command = std::move(x.m_tc_assignment_command);
        m_tc_assignment_loc_latitude = x.m_tc_assignment_loc_latitude;
        m_tc_assignment_loc_longitude = x.m_tc_assignment_loc_longitude;
        m_tc_assignment_loc_altitude = x.m_tc_assignment_loc_altitude;
        m_tc_assignment_loc_time_seconds = x.m_tc_assignment_loc_time_seconds;
        m_tc_assignment_loc_time_nano_seconds = x.m_tc_assignment_loc_time_nano_seconds;
        m_tc_assignment_loc_speed_mps = x.m_tc_assignment_loc_speed_mps;
        m_tc_assignment_loc_orientation_degrees = x.m_tc_assignment_loc_orientation_degrees;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object FlatMessagingPacket that will be copied.
     */
    eProsima_user_DllExport FlatMessagingPacket& operator =(
            const FlatMessagingPacket& x)
    {

                    m_message_type = x.m_message_type;

                    m_sr_header_sender_id = x.m_sr_header_sender_id;

                    m_sr_header_time_seconds = x.m_sr_header_time_seconds;

                    m_sr_header_time_nano_seconds = x.m_sr_header_time_nano_seconds;

                    m_sr_location_latitude = x.m_sr_location_latitude;

                    m_sr_location_longitude = x.m_sr_location_longitude;

                    m_sr_location_altitude = x.m_sr_location_altitude;

                    m_sr_location_time_seconds = x.m_sr_location_time_seconds;

                    m_sr_location_time_nano_seconds = x.m_sr_location_time_nano_seconds;

                    m_sr_location_speed_mps = x.m_sr_location_speed_mps;

                    m_sr_location_orientation_degrees = x.m_sr_location_orientation_degrees;

                    m_sr_status_task_status = x.m_sr_status_task_status;

                    m_sr_status_battery_percentage = x.m_sr_status_battery_percentage;

                    m_sr_status_signal_strength_dbm = x.m_sr_status_signal_strength_dbm;

                    m_sr_status_system_error = x.m_sr_status_system_error;

                    m_cd_header_sender_id = x.m_cd_header_sender_id;

                    m_cd_header_time_seconds = x.m_cd_header_time_seconds;

                    m_cd_header_time_nano_seconds = x.m_cd_header_time_nano_seconds;

                    m_cd_detection_target_ID = x.m_cd_detection_target_ID;

                    m_cd_detection_target_type = x.m_cd_detection_target_type;

                    m_cd_detection_loc_latitude = x.m_cd_detection_loc_latitude;

                    m_cd_detection_loc_longitude = x.m_cd_detection_loc_longitude;

                    m_cd_detection_loc_altitude = x.m_cd_detection_loc_altitude;

                    m_cd_detection_loc_time_seconds = x.m_cd_detection_loc_time_seconds;

                    m_cd_detection_loc_time_nano_seconds = x.m_cd_detection_loc_time_nano_seconds;

                    m_cd_detection_loc_speed_mps = x.m_cd_detection_loc_speed_mps;

                    m_cd_detection_loc_orientation_degrees = x.m_cd_detection_loc_orientation_degrees;

                    m_cd_detection_confidence_level = x.m_cd_detection_confidence_level;

                    m_cd_detection_description = x.m_cd_detection_description;

                    m_cd_detection_raw_data_link = x.m_cd_detection_raw_data_link;

                    m_tc_header_sender_id = x.m_tc_header_sender_id;

                    m_tc_header_time_seconds = x.m_tc_header_time_seconds;

                    m_tc_header_time_nano_seconds = x.m_tc_header_time_nano_seconds;

                    m_tc_receiver_id = x.m_tc_receiver_id;

                    m_tc_assignment_command = x.m_tc_assignment_command;

                    m_tc_assignment_loc_latitude = x.m_tc_assignment_loc_latitude;

                    m_tc_assignment_loc_longitude = x.m_tc_assignment_loc_longitude;

                    m_tc_assignment_loc_altitude = x.m_tc_assignment_loc_altitude;

                    m_tc_assignment_loc_time_seconds = x.m_tc_assignment_loc_time_seconds;

                    m_tc_assignment_loc_time_nano_seconds = x.m_tc_assignment_loc_time_nano_seconds;

                    m_tc_assignment_loc_speed_mps = x.m_tc_assignment_loc_speed_mps;

                    m_tc_assignment_loc_orientation_degrees = x.m_tc_assignment_loc_orientation_degrees;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object FlatMessagingPacket that will be copied.
     */
    eProsima_user_DllExport FlatMessagingPacket& operator =(
            FlatMessagingPacket&& x) noexcept
    {

        m_message_type = x.m_message_type;
        m_sr_header_sender_id = std::move(x.m_sr_header_sender_id);
        m_sr_header_time_seconds = x.m_sr_header_time_seconds;
        m_sr_header_time_nano_seconds = x.m_sr_header_time_nano_seconds;
        m_sr_location_latitude = x.m_sr_location_latitude;
        m_sr_location_longitude = x.m_sr_location_longitude;
        m_sr_location_altitude = x.m_sr_location_altitude;
        m_sr_location_time_seconds = x.m_sr_location_time_seconds;
        m_sr_location_time_nano_seconds = x.m_sr_location_time_nano_seconds;
        m_sr_location_speed_mps = x.m_sr_location_speed_mps;
        m_sr_location_orientation_degrees = x.m_sr_location_orientation_degrees;
        m_sr_status_task_status = x.m_sr_status_task_status;
        m_sr_status_battery_percentage = x.m_sr_status_battery_percentage;
        m_sr_status_signal_strength_dbm = x.m_sr_status_signal_strength_dbm;
        m_sr_status_system_error = x.m_sr_status_system_error;
        m_cd_header_sender_id = std::move(x.m_cd_header_sender_id);
        m_cd_header_time_seconds = x.m_cd_header_time_seconds;
        m_cd_header_time_nano_seconds = x.m_cd_header_time_nano_seconds;
        m_cd_detection_target_ID = std::move(x.m_cd_detection_target_ID);
        m_cd_detection_target_type = x.m_cd_detection_target_type;
        m_cd_detection_loc_latitude = x.m_cd_detection_loc_latitude;
        m_cd_detection_loc_longitude = x.m_cd_detection_loc_longitude;
        m_cd_detection_loc_altitude = x.m_cd_detection_loc_altitude;
        m_cd_detection_loc_time_seconds = x.m_cd_detection_loc_time_seconds;
        m_cd_detection_loc_time_nano_seconds = x.m_cd_detection_loc_time_nano_seconds;
        m_cd_detection_loc_speed_mps = x.m_cd_detection_loc_speed_mps;
        m_cd_detection_loc_orientation_degrees = x.m_cd_detection_loc_orientation_degrees;
        m_cd_detection_confidence_level = x.m_cd_detection_confidence_level;
        m_cd_detection_description = std::move(x.m_cd_detection_description);
        m_cd_detection_raw_data_link = std::move(x.m_cd_detection_raw_data_link);
        m_tc_header_sender_id = std::move(x.m_tc_header_sender_id);
        m_tc_header_time_seconds = x.m_tc_header_time_seconds;
        m_tc_header_time_nano_seconds = x.m_tc_header_time_nano_seconds;
        m_tc_receiver_id = std::move(x.m_tc_receiver_id);
        m_tc_assignment_command = std::move(x.m_tc_assignment_command);
        m_tc_assignment_loc_latitude = x.m_tc_assignment_loc_latitude;
        m_tc_assignment_loc_longitude = x.m_tc_assignment_loc_longitude;
        m_tc_assignment_loc_altitude = x.m_tc_assignment_loc_altitude;
        m_tc_assignment_loc_time_seconds = x.m_tc_assignment_loc_time_seconds;
        m_tc_assignment_loc_time_nano_seconds = x.m_tc_assignment_loc_time_nano_seconds;
        m_tc_assignment_loc_speed_mps = x.m_tc_assignment_loc_speed_mps;
        m_tc_assignment_loc_orientation_degrees = x.m_tc_assignment_loc_orientation_degrees;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x FlatMessagingPacket object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const FlatMessagingPacket& x) const
    {
        return (m_message_type == x.m_message_type &&
           m_sr_header_sender_id == x.m_sr_header_sender_id &&
           m_sr_header_time_seconds == x.m_sr_header_time_seconds &&
           m_sr_header_time_nano_seconds == x.m_sr_header_time_nano_seconds &&
           m_sr_location_latitude == x.m_sr_location_latitude &&
           m_sr_location_longitude == x.m_sr_location_longitude &&
           m_sr_location_altitude == x.m_sr_location_altitude &&
           m_sr_location_time_seconds == x.m_sr_location_time_seconds &&
           m_sr_location_time_nano_seconds == x.m_sr_location_time_nano_seconds &&
           m_sr_location_speed_mps == x.m_sr_location_speed_mps &&
           m_sr_location_orientation_degrees == x.m_sr_location_orientation_degrees &&
           m_sr_status_task_status == x.m_sr_status_task_status &&
           m_sr_status_battery_percentage == x.m_sr_status_battery_percentage &&
           m_sr_status_signal_strength_dbm == x.m_sr_status_signal_strength_dbm &&
           m_sr_status_system_error == x.m_sr_status_system_error &&
           m_cd_header_sender_id == x.m_cd_header_sender_id &&
           m_cd_header_time_seconds == x.m_cd_header_time_seconds &&
           m_cd_header_time_nano_seconds == x.m_cd_header_time_nano_seconds &&
           m_cd_detection_target_ID == x.m_cd_detection_target_ID &&
           m_cd_detection_target_type == x.m_cd_detection_target_type &&
           m_cd_detection_loc_latitude == x.m_cd_detection_loc_latitude &&
           m_cd_detection_loc_longitude == x.m_cd_detection_loc_longitude &&
           m_cd_detection_loc_altitude == x.m_cd_detection_loc_altitude &&
           m_cd_detection_loc_time_seconds == x.m_cd_detection_loc_time_seconds &&
           m_cd_detection_loc_time_nano_seconds == x.m_cd_detection_loc_time_nano_seconds &&
           m_cd_detection_loc_speed_mps == x.m_cd_detection_loc_speed_mps &&
           m_cd_detection_loc_orientation_degrees == x.m_cd_detection_loc_orientation_degrees &&
           m_cd_detection_confidence_level == x.m_cd_detection_confidence_level &&
           m_cd_detection_description == x.m_cd_detection_description &&
           m_cd_detection_raw_data_link == x.m_cd_detection_raw_data_link &&
           m_tc_header_sender_id == x.m_tc_header_sender_id &&
           m_tc_header_time_seconds == x.m_tc_header_time_seconds &&
           m_tc_header_time_nano_seconds == x.m_tc_header_time_nano_seconds &&
           m_tc_receiver_id == x.m_tc_receiver_id &&
           m_tc_assignment_command == x.m_tc_assignment_command &&
           m_tc_assignment_loc_latitude == x.m_tc_assignment_loc_latitude &&
           m_tc_assignment_loc_longitude == x.m_tc_assignment_loc_longitude &&
           m_tc_assignment_loc_altitude == x.m_tc_assignment_loc_altitude &&
           m_tc_assignment_loc_time_seconds == x.m_tc_assignment_loc_time_seconds &&
           m_tc_assignment_loc_time_nano_seconds == x.m_tc_assignment_loc_time_nano_seconds &&
           m_tc_assignment_loc_speed_mps == x.m_tc_assignment_loc_speed_mps &&
           m_tc_assignment_loc_orientation_degrees == x.m_tc_assignment_loc_orientation_degrees);
    }

    /*!
     * @brief Comparison operator.
     * @param x FlatMessagingPacket object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const FlatMessagingPacket& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member message_type
     * @param _message_type New value for member message_type
     */
    eProsima_user_DllExport void message_type(
            int16_t _message_type)
    {
        m_message_type = _message_type;
    }

    /*!
     * @brief This function returns the value of member message_type
     * @return Value of member message_type
     */
    eProsima_user_DllExport int16_t message_type() const
    {
        return m_message_type;
    }

    /*!
     * @brief This function returns a reference to member message_type
     * @return Reference to member message_type
     */
    eProsima_user_DllExport int16_t& message_type()
    {
        return m_message_type;
    }


    /*!
     * @brief This function copies the value in member sr_header_sender_id
     * @param _sr_header_sender_id New value to be copied in member sr_header_sender_id
     */
    eProsima_user_DllExport void sr_header_sender_id(
            const std::string& _sr_header_sender_id)
    {
        m_sr_header_sender_id = _sr_header_sender_id;
    }

    /*!
     * @brief This function moves the value in member sr_header_sender_id
     * @param _sr_header_sender_id New value to be moved in member sr_header_sender_id
     */
    eProsima_user_DllExport void sr_header_sender_id(
            std::string&& _sr_header_sender_id)
    {
        m_sr_header_sender_id = std::move(_sr_header_sender_id);
    }

    /*!
     * @brief This function returns a constant reference to member sr_header_sender_id
     * @return Constant reference to member sr_header_sender_id
     */
    eProsima_user_DllExport const std::string& sr_header_sender_id() const
    {
        return m_sr_header_sender_id;
    }

    /*!
     * @brief This function returns a reference to member sr_header_sender_id
     * @return Reference to member sr_header_sender_id
     */
    eProsima_user_DllExport std::string& sr_header_sender_id()
    {
        return m_sr_header_sender_id;
    }


    /*!
     * @brief This function sets a value in member sr_header_time_seconds
     * @param _sr_header_time_seconds New value for member sr_header_time_seconds
     */
    eProsima_user_DllExport void sr_header_time_seconds(
            int32_t _sr_header_time_seconds)
    {
        m_sr_header_time_seconds = _sr_header_time_seconds;
    }

    /*!
     * @brief This function returns the value of member sr_header_time_seconds
     * @return Value of member sr_header_time_seconds
     */
    eProsima_user_DllExport int32_t sr_header_time_seconds() const
    {
        return m_sr_header_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member sr_header_time_seconds
     * @return Reference to member sr_header_time_seconds
     */
    eProsima_user_DllExport int32_t& sr_header_time_seconds()
    {
        return m_sr_header_time_seconds;
    }


    /*!
     * @brief This function sets a value in member sr_header_time_nano_seconds
     * @param _sr_header_time_nano_seconds New value for member sr_header_time_nano_seconds
     */
    eProsima_user_DllExport void sr_header_time_nano_seconds(
            uint32_t _sr_header_time_nano_seconds)
    {
        m_sr_header_time_nano_seconds = _sr_header_time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member sr_header_time_nano_seconds
     * @return Value of member sr_header_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t sr_header_time_nano_seconds() const
    {
        return m_sr_header_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member sr_header_time_nano_seconds
     * @return Reference to member sr_header_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& sr_header_time_nano_seconds()
    {
        return m_sr_header_time_nano_seconds;
    }


    /*!
     * @brief This function sets a value in member sr_location_latitude
     * @param _sr_location_latitude New value for member sr_location_latitude
     */
    eProsima_user_DllExport void sr_location_latitude(
            double _sr_location_latitude)
    {
        m_sr_location_latitude = _sr_location_latitude;
    }

    /*!
     * @brief This function returns the value of member sr_location_latitude
     * @return Value of member sr_location_latitude
     */
    eProsima_user_DllExport double sr_location_latitude() const
    {
        return m_sr_location_latitude;
    }

    /*!
     * @brief This function returns a reference to member sr_location_latitude
     * @return Reference to member sr_location_latitude
     */
    eProsima_user_DllExport double& sr_location_latitude()
    {
        return m_sr_location_latitude;
    }


    /*!
     * @brief This function sets a value in member sr_location_longitude
     * @param _sr_location_longitude New value for member sr_location_longitude
     */
    eProsima_user_DllExport void sr_location_longitude(
            double _sr_location_longitude)
    {
        m_sr_location_longitude = _sr_location_longitude;
    }

    /*!
     * @brief This function returns the value of member sr_location_longitude
     * @return Value of member sr_location_longitude
     */
    eProsima_user_DllExport double sr_location_longitude() const
    {
        return m_sr_location_longitude;
    }

    /*!
     * @brief This function returns a reference to member sr_location_longitude
     * @return Reference to member sr_location_longitude
     */
    eProsima_user_DllExport double& sr_location_longitude()
    {
        return m_sr_location_longitude;
    }


    /*!
     * @brief This function sets a value in member sr_location_altitude
     * @param _sr_location_altitude New value for member sr_location_altitude
     */
    eProsima_user_DllExport void sr_location_altitude(
            float _sr_location_altitude)
    {
        m_sr_location_altitude = _sr_location_altitude;
    }

    /*!
     * @brief This function returns the value of member sr_location_altitude
     * @return Value of member sr_location_altitude
     */
    eProsima_user_DllExport float sr_location_altitude() const
    {
        return m_sr_location_altitude;
    }

    /*!
     * @brief This function returns a reference to member sr_location_altitude
     * @return Reference to member sr_location_altitude
     */
    eProsima_user_DllExport float& sr_location_altitude()
    {
        return m_sr_location_altitude;
    }


    /*!
     * @brief This function sets a value in member sr_location_time_seconds
     * @param _sr_location_time_seconds New value for member sr_location_time_seconds
     */
    eProsima_user_DllExport void sr_location_time_seconds(
            int32_t _sr_location_time_seconds)
    {
        m_sr_location_time_seconds = _sr_location_time_seconds;
    }

    /*!
     * @brief This function returns the value of member sr_location_time_seconds
     * @return Value of member sr_location_time_seconds
     */
    eProsima_user_DllExport int32_t sr_location_time_seconds() const
    {
        return m_sr_location_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member sr_location_time_seconds
     * @return Reference to member sr_location_time_seconds
     */
    eProsima_user_DllExport int32_t& sr_location_time_seconds()
    {
        return m_sr_location_time_seconds;
    }


    /*!
     * @brief This function sets a value in member sr_location_time_nano_seconds
     * @param _sr_location_time_nano_seconds New value for member sr_location_time_nano_seconds
     */
    eProsima_user_DllExport void sr_location_time_nano_seconds(
            uint32_t _sr_location_time_nano_seconds)
    {
        m_sr_location_time_nano_seconds = _sr_location_time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member sr_location_time_nano_seconds
     * @return Value of member sr_location_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t sr_location_time_nano_seconds() const
    {
        return m_sr_location_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member sr_location_time_nano_seconds
     * @return Reference to member sr_location_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& sr_location_time_nano_seconds()
    {
        return m_sr_location_time_nano_seconds;
    }


    /*!
     * @brief This function sets a value in member sr_location_speed_mps
     * @param _sr_location_speed_mps New value for member sr_location_speed_mps
     */
    eProsima_user_DllExport void sr_location_speed_mps(
            float _sr_location_speed_mps)
    {
        m_sr_location_speed_mps = _sr_location_speed_mps;
    }

    /*!
     * @brief This function returns the value of member sr_location_speed_mps
     * @return Value of member sr_location_speed_mps
     */
    eProsima_user_DllExport float sr_location_speed_mps() const
    {
        return m_sr_location_speed_mps;
    }

    /*!
     * @brief This function returns a reference to member sr_location_speed_mps
     * @return Reference to member sr_location_speed_mps
     */
    eProsima_user_DllExport float& sr_location_speed_mps()
    {
        return m_sr_location_speed_mps;
    }


    /*!
     * @brief This function sets a value in member sr_location_orientation_degrees
     * @param _sr_location_orientation_degrees New value for member sr_location_orientation_degrees
     */
    eProsima_user_DllExport void sr_location_orientation_degrees(
            int16_t _sr_location_orientation_degrees)
    {
        m_sr_location_orientation_degrees = _sr_location_orientation_degrees;
    }

    /*!
     * @brief This function returns the value of member sr_location_orientation_degrees
     * @return Value of member sr_location_orientation_degrees
     */
    eProsima_user_DllExport int16_t sr_location_orientation_degrees() const
    {
        return m_sr_location_orientation_degrees;
    }

    /*!
     * @brief This function returns a reference to member sr_location_orientation_degrees
     * @return Reference to member sr_location_orientation_degrees
     */
    eProsima_user_DllExport int16_t& sr_location_orientation_degrees()
    {
        return m_sr_location_orientation_degrees;
    }


    /*!
     * @brief This function sets a value in member sr_status_task_status
     * @param _sr_status_task_status New value for member sr_status_task_status
     */
    eProsima_user_DllExport void sr_status_task_status(
            int16_t _sr_status_task_status)
    {
        m_sr_status_task_status = _sr_status_task_status;
    }

    /*!
     * @brief This function returns the value of member sr_status_task_status
     * @return Value of member sr_status_task_status
     */
    eProsima_user_DllExport int16_t sr_status_task_status() const
    {
        return m_sr_status_task_status;
    }

    /*!
     * @brief This function returns a reference to member sr_status_task_status
     * @return Reference to member sr_status_task_status
     */
    eProsima_user_DllExport int16_t& sr_status_task_status()
    {
        return m_sr_status_task_status;
    }


    /*!
     * @brief This function sets a value in member sr_status_battery_percentage
     * @param _sr_status_battery_percentage New value for member sr_status_battery_percentage
     */
    eProsima_user_DllExport void sr_status_battery_percentage(
            uint16_t _sr_status_battery_percentage)
    {
        m_sr_status_battery_percentage = _sr_status_battery_percentage;
    }

    /*!
     * @brief This function returns the value of member sr_status_battery_percentage
     * @return Value of member sr_status_battery_percentage
     */
    eProsima_user_DllExport uint16_t sr_status_battery_percentage() const
    {
        return m_sr_status_battery_percentage;
    }

    /*!
     * @brief This function returns a reference to member sr_status_battery_percentage
     * @return Reference to member sr_status_battery_percentage
     */
    eProsima_user_DllExport uint16_t& sr_status_battery_percentage()
    {
        return m_sr_status_battery_percentage;
    }


    /*!
     * @brief This function sets a value in member sr_status_signal_strength_dbm
     * @param _sr_status_signal_strength_dbm New value for member sr_status_signal_strength_dbm
     */
    eProsima_user_DllExport void sr_status_signal_strength_dbm(
            float _sr_status_signal_strength_dbm)
    {
        m_sr_status_signal_strength_dbm = _sr_status_signal_strength_dbm;
    }

    /*!
     * @brief This function returns the value of member sr_status_signal_strength_dbm
     * @return Value of member sr_status_signal_strength_dbm
     */
    eProsima_user_DllExport float sr_status_signal_strength_dbm() const
    {
        return m_sr_status_signal_strength_dbm;
    }

    /*!
     * @brief This function returns a reference to member sr_status_signal_strength_dbm
     * @return Reference to member sr_status_signal_strength_dbm
     */
    eProsima_user_DllExport float& sr_status_signal_strength_dbm()
    {
        return m_sr_status_signal_strength_dbm;
    }


    /*!
     * @brief This function sets a value in member sr_status_system_error
     * @param _sr_status_system_error New value for member sr_status_system_error
     */
    eProsima_user_DllExport void sr_status_system_error(
            bool _sr_status_system_error)
    {
        m_sr_status_system_error = _sr_status_system_error;
    }

    /*!
     * @brief This function returns the value of member sr_status_system_error
     * @return Value of member sr_status_system_error
     */
    eProsima_user_DllExport bool sr_status_system_error() const
    {
        return m_sr_status_system_error;
    }

    /*!
     * @brief This function returns a reference to member sr_status_system_error
     * @return Reference to member sr_status_system_error
     */
    eProsima_user_DllExport bool& sr_status_system_error()
    {
        return m_sr_status_system_error;
    }


    /*!
     * @brief This function copies the value in member cd_header_sender_id
     * @param _cd_header_sender_id New value to be copied in member cd_header_sender_id
     */
    eProsima_user_DllExport void cd_header_sender_id(
            const std::string& _cd_header_sender_id)
    {
        m_cd_header_sender_id = _cd_header_sender_id;
    }

    /*!
     * @brief This function moves the value in member cd_header_sender_id
     * @param _cd_header_sender_id New value to be moved in member cd_header_sender_id
     */
    eProsima_user_DllExport void cd_header_sender_id(
            std::string&& _cd_header_sender_id)
    {
        m_cd_header_sender_id = std::move(_cd_header_sender_id);
    }

    /*!
     * @brief This function returns a constant reference to member cd_header_sender_id
     * @return Constant reference to member cd_header_sender_id
     */
    eProsima_user_DllExport const std::string& cd_header_sender_id() const
    {
        return m_cd_header_sender_id;
    }

    /*!
     * @brief This function returns a reference to member cd_header_sender_id
     * @return Reference to member cd_header_sender_id
     */
    eProsima_user_DllExport std::string& cd_header_sender_id()
    {
        return m_cd_header_sender_id;
    }


    /*!
     * @brief This function sets a value in member cd_header_time_seconds
     * @param _cd_header_time_seconds New value for member cd_header_time_seconds
     */
    eProsima_user_DllExport void cd_header_time_seconds(
            int32_t _cd_header_time_seconds)
    {
        m_cd_header_time_seconds = _cd_header_time_seconds;
    }

    /*!
     * @brief This function returns the value of member cd_header_time_seconds
     * @return Value of member cd_header_time_seconds
     */
    eProsima_user_DllExport int32_t cd_header_time_seconds() const
    {
        return m_cd_header_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member cd_header_time_seconds
     * @return Reference to member cd_header_time_seconds
     */
    eProsima_user_DllExport int32_t& cd_header_time_seconds()
    {
        return m_cd_header_time_seconds;
    }


    /*!
     * @brief This function sets a value in member cd_header_time_nano_seconds
     * @param _cd_header_time_nano_seconds New value for member cd_header_time_nano_seconds
     */
    eProsima_user_DllExport void cd_header_time_nano_seconds(
            uint32_t _cd_header_time_nano_seconds)
    {
        m_cd_header_time_nano_seconds = _cd_header_time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member cd_header_time_nano_seconds
     * @return Value of member cd_header_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t cd_header_time_nano_seconds() const
    {
        return m_cd_header_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member cd_header_time_nano_seconds
     * @return Reference to member cd_header_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& cd_header_time_nano_seconds()
    {
        return m_cd_header_time_nano_seconds;
    }


    /*!
     * @brief This function copies the value in member cd_detection_target_ID
     * @param _cd_detection_target_ID New value to be copied in member cd_detection_target_ID
     */
    eProsima_user_DllExport void cd_detection_target_ID(
            const std::string& _cd_detection_target_ID)
    {
        m_cd_detection_target_ID = _cd_detection_target_ID;
    }

    /*!
     * @brief This function moves the value in member cd_detection_target_ID
     * @param _cd_detection_target_ID New value to be moved in member cd_detection_target_ID
     */
    eProsima_user_DllExport void cd_detection_target_ID(
            std::string&& _cd_detection_target_ID)
    {
        m_cd_detection_target_ID = std::move(_cd_detection_target_ID);
    }

    /*!
     * @brief This function returns a constant reference to member cd_detection_target_ID
     * @return Constant reference to member cd_detection_target_ID
     */
    eProsima_user_DllExport const std::string& cd_detection_target_ID() const
    {
        return m_cd_detection_target_ID;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_target_ID
     * @return Reference to member cd_detection_target_ID
     */
    eProsima_user_DllExport std::string& cd_detection_target_ID()
    {
        return m_cd_detection_target_ID;
    }


    /*!
     * @brief This function sets a value in member cd_detection_target_type
     * @param _cd_detection_target_type New value for member cd_detection_target_type
     */
    eProsima_user_DllExport void cd_detection_target_type(
            int16_t _cd_detection_target_type)
    {
        m_cd_detection_target_type = _cd_detection_target_type;
    }

    /*!
     * @brief This function returns the value of member cd_detection_target_type
     * @return Value of member cd_detection_target_type
     */
    eProsima_user_DllExport int16_t cd_detection_target_type() const
    {
        return m_cd_detection_target_type;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_target_type
     * @return Reference to member cd_detection_target_type
     */
    eProsima_user_DllExport int16_t& cd_detection_target_type()
    {
        return m_cd_detection_target_type;
    }


    /*!
     * @brief This function sets a value in member cd_detection_loc_latitude
     * @param _cd_detection_loc_latitude New value for member cd_detection_loc_latitude
     */
    eProsima_user_DllExport void cd_detection_loc_latitude(
            double _cd_detection_loc_latitude)
    {
        m_cd_detection_loc_latitude = _cd_detection_loc_latitude;
    }

    /*!
     * @brief This function returns the value of member cd_detection_loc_latitude
     * @return Value of member cd_detection_loc_latitude
     */
    eProsima_user_DllExport double cd_detection_loc_latitude() const
    {
        return m_cd_detection_loc_latitude;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_loc_latitude
     * @return Reference to member cd_detection_loc_latitude
     */
    eProsima_user_DllExport double& cd_detection_loc_latitude()
    {
        return m_cd_detection_loc_latitude;
    }


    /*!
     * @brief This function sets a value in member cd_detection_loc_longitude
     * @param _cd_detection_loc_longitude New value for member cd_detection_loc_longitude
     */
    eProsima_user_DllExport void cd_detection_loc_longitude(
            double _cd_detection_loc_longitude)
    {
        m_cd_detection_loc_longitude = _cd_detection_loc_longitude;
    }

    /*!
     * @brief This function returns the value of member cd_detection_loc_longitude
     * @return Value of member cd_detection_loc_longitude
     */
    eProsima_user_DllExport double cd_detection_loc_longitude() const
    {
        return m_cd_detection_loc_longitude;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_loc_longitude
     * @return Reference to member cd_detection_loc_longitude
     */
    eProsima_user_DllExport double& cd_detection_loc_longitude()
    {
        return m_cd_detection_loc_longitude;
    }


    /*!
     * @brief This function sets a value in member cd_detection_loc_altitude
     * @param _cd_detection_loc_altitude New value for member cd_detection_loc_altitude
     */
    eProsima_user_DllExport void cd_detection_loc_altitude(
            float _cd_detection_loc_altitude)
    {
        m_cd_detection_loc_altitude = _cd_detection_loc_altitude;
    }

    /*!
     * @brief This function returns the value of member cd_detection_loc_altitude
     * @return Value of member cd_detection_loc_altitude
     */
    eProsima_user_DllExport float cd_detection_loc_altitude() const
    {
        return m_cd_detection_loc_altitude;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_loc_altitude
     * @return Reference to member cd_detection_loc_altitude
     */
    eProsima_user_DllExport float& cd_detection_loc_altitude()
    {
        return m_cd_detection_loc_altitude;
    }


    /*!
     * @brief This function sets a value in member cd_detection_loc_time_seconds
     * @param _cd_detection_loc_time_seconds New value for member cd_detection_loc_time_seconds
     */
    eProsima_user_DllExport void cd_detection_loc_time_seconds(
            int32_t _cd_detection_loc_time_seconds)
    {
        m_cd_detection_loc_time_seconds = _cd_detection_loc_time_seconds;
    }

    /*!
     * @brief This function returns the value of member cd_detection_loc_time_seconds
     * @return Value of member cd_detection_loc_time_seconds
     */
    eProsima_user_DllExport int32_t cd_detection_loc_time_seconds() const
    {
        return m_cd_detection_loc_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_loc_time_seconds
     * @return Reference to member cd_detection_loc_time_seconds
     */
    eProsima_user_DllExport int32_t& cd_detection_loc_time_seconds()
    {
        return m_cd_detection_loc_time_seconds;
    }


    /*!
     * @brief This function sets a value in member cd_detection_loc_time_nano_seconds
     * @param _cd_detection_loc_time_nano_seconds New value for member cd_detection_loc_time_nano_seconds
     */
    eProsima_user_DllExport void cd_detection_loc_time_nano_seconds(
            uint32_t _cd_detection_loc_time_nano_seconds)
    {
        m_cd_detection_loc_time_nano_seconds = _cd_detection_loc_time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member cd_detection_loc_time_nano_seconds
     * @return Value of member cd_detection_loc_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t cd_detection_loc_time_nano_seconds() const
    {
        return m_cd_detection_loc_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_loc_time_nano_seconds
     * @return Reference to member cd_detection_loc_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& cd_detection_loc_time_nano_seconds()
    {
        return m_cd_detection_loc_time_nano_seconds;
    }


    /*!
     * @brief This function sets a value in member cd_detection_loc_speed_mps
     * @param _cd_detection_loc_speed_mps New value for member cd_detection_loc_speed_mps
     */
    eProsima_user_DllExport void cd_detection_loc_speed_mps(
            float _cd_detection_loc_speed_mps)
    {
        m_cd_detection_loc_speed_mps = _cd_detection_loc_speed_mps;
    }

    /*!
     * @brief This function returns the value of member cd_detection_loc_speed_mps
     * @return Value of member cd_detection_loc_speed_mps
     */
    eProsima_user_DllExport float cd_detection_loc_speed_mps() const
    {
        return m_cd_detection_loc_speed_mps;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_loc_speed_mps
     * @return Reference to member cd_detection_loc_speed_mps
     */
    eProsima_user_DllExport float& cd_detection_loc_speed_mps()
    {
        return m_cd_detection_loc_speed_mps;
    }


    /*!
     * @brief This function sets a value in member cd_detection_loc_orientation_degrees
     * @param _cd_detection_loc_orientation_degrees New value for member cd_detection_loc_orientation_degrees
     */
    eProsima_user_DllExport void cd_detection_loc_orientation_degrees(
            int16_t _cd_detection_loc_orientation_degrees)
    {
        m_cd_detection_loc_orientation_degrees = _cd_detection_loc_orientation_degrees;
    }

    /*!
     * @brief This function returns the value of member cd_detection_loc_orientation_degrees
     * @return Value of member cd_detection_loc_orientation_degrees
     */
    eProsima_user_DllExport int16_t cd_detection_loc_orientation_degrees() const
    {
        return m_cd_detection_loc_orientation_degrees;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_loc_orientation_degrees
     * @return Reference to member cd_detection_loc_orientation_degrees
     */
    eProsima_user_DllExport int16_t& cd_detection_loc_orientation_degrees()
    {
        return m_cd_detection_loc_orientation_degrees;
    }


    /*!
     * @brief This function sets a value in member cd_detection_confidence_level
     * @param _cd_detection_confidence_level New value for member cd_detection_confidence_level
     */
    eProsima_user_DllExport void cd_detection_confidence_level(
            float _cd_detection_confidence_level)
    {
        m_cd_detection_confidence_level = _cd_detection_confidence_level;
    }

    /*!
     * @brief This function returns the value of member cd_detection_confidence_level
     * @return Value of member cd_detection_confidence_level
     */
    eProsima_user_DllExport float cd_detection_confidence_level() const
    {
        return m_cd_detection_confidence_level;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_confidence_level
     * @return Reference to member cd_detection_confidence_level
     */
    eProsima_user_DllExport float& cd_detection_confidence_level()
    {
        return m_cd_detection_confidence_level;
    }


    /*!
     * @brief This function copies the value in member cd_detection_description
     * @param _cd_detection_description New value to be copied in member cd_detection_description
     */
    eProsima_user_DllExport void cd_detection_description(
            const std::string& _cd_detection_description)
    {
        m_cd_detection_description = _cd_detection_description;
    }

    /*!
     * @brief This function moves the value in member cd_detection_description
     * @param _cd_detection_description New value to be moved in member cd_detection_description
     */
    eProsima_user_DllExport void cd_detection_description(
            std::string&& _cd_detection_description)
    {
        m_cd_detection_description = std::move(_cd_detection_description);
    }

    /*!
     * @brief This function returns a constant reference to member cd_detection_description
     * @return Constant reference to member cd_detection_description
     */
    eProsima_user_DllExport const std::string& cd_detection_description() const
    {
        return m_cd_detection_description;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_description
     * @return Reference to member cd_detection_description
     */
    eProsima_user_DllExport std::string& cd_detection_description()
    {
        return m_cd_detection_description;
    }


    /*!
     * @brief This function copies the value in member cd_detection_raw_data_link
     * @param _cd_detection_raw_data_link New value to be copied in member cd_detection_raw_data_link
     */
    eProsima_user_DllExport void cd_detection_raw_data_link(
            const std::string& _cd_detection_raw_data_link)
    {
        m_cd_detection_raw_data_link = _cd_detection_raw_data_link;
    }

    /*!
     * @brief This function moves the value in member cd_detection_raw_data_link
     * @param _cd_detection_raw_data_link New value to be moved in member cd_detection_raw_data_link
     */
    eProsima_user_DllExport void cd_detection_raw_data_link(
            std::string&& _cd_detection_raw_data_link)
    {
        m_cd_detection_raw_data_link = std::move(_cd_detection_raw_data_link);
    }

    /*!
     * @brief This function returns a constant reference to member cd_detection_raw_data_link
     * @return Constant reference to member cd_detection_raw_data_link
     */
    eProsima_user_DllExport const std::string& cd_detection_raw_data_link() const
    {
        return m_cd_detection_raw_data_link;
    }

    /*!
     * @brief This function returns a reference to member cd_detection_raw_data_link
     * @return Reference to member cd_detection_raw_data_link
     */
    eProsima_user_DllExport std::string& cd_detection_raw_data_link()
    {
        return m_cd_detection_raw_data_link;
    }


    /*!
     * @brief This function copies the value in member tc_header_sender_id
     * @param _tc_header_sender_id New value to be copied in member tc_header_sender_id
     */
    eProsima_user_DllExport void tc_header_sender_id(
            const std::string& _tc_header_sender_id)
    {
        m_tc_header_sender_id = _tc_header_sender_id;
    }

    /*!
     * @brief This function moves the value in member tc_header_sender_id
     * @param _tc_header_sender_id New value to be moved in member tc_header_sender_id
     */
    eProsima_user_DllExport void tc_header_sender_id(
            std::string&& _tc_header_sender_id)
    {
        m_tc_header_sender_id = std::move(_tc_header_sender_id);
    }

    /*!
     * @brief This function returns a constant reference to member tc_header_sender_id
     * @return Constant reference to member tc_header_sender_id
     */
    eProsima_user_DllExport const std::string& tc_header_sender_id() const
    {
        return m_tc_header_sender_id;
    }

    /*!
     * @brief This function returns a reference to member tc_header_sender_id
     * @return Reference to member tc_header_sender_id
     */
    eProsima_user_DllExport std::string& tc_header_sender_id()
    {
        return m_tc_header_sender_id;
    }


    /*!
     * @brief This function sets a value in member tc_header_time_seconds
     * @param _tc_header_time_seconds New value for member tc_header_time_seconds
     */
    eProsima_user_DllExport void tc_header_time_seconds(
            int32_t _tc_header_time_seconds)
    {
        m_tc_header_time_seconds = _tc_header_time_seconds;
    }

    /*!
     * @brief This function returns the value of member tc_header_time_seconds
     * @return Value of member tc_header_time_seconds
     */
    eProsima_user_DllExport int32_t tc_header_time_seconds() const
    {
        return m_tc_header_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member tc_header_time_seconds
     * @return Reference to member tc_header_time_seconds
     */
    eProsima_user_DllExport int32_t& tc_header_time_seconds()
    {
        return m_tc_header_time_seconds;
    }


    /*!
     * @brief This function sets a value in member tc_header_time_nano_seconds
     * @param _tc_header_time_nano_seconds New value for member tc_header_time_nano_seconds
     */
    eProsima_user_DllExport void tc_header_time_nano_seconds(
            uint32_t _tc_header_time_nano_seconds)
    {
        m_tc_header_time_nano_seconds = _tc_header_time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member tc_header_time_nano_seconds
     * @return Value of member tc_header_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t tc_header_time_nano_seconds() const
    {
        return m_tc_header_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member tc_header_time_nano_seconds
     * @return Reference to member tc_header_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& tc_header_time_nano_seconds()
    {
        return m_tc_header_time_nano_seconds;
    }


    /*!
     * @brief This function copies the value in member tc_receiver_id
     * @param _tc_receiver_id New value to be copied in member tc_receiver_id
     */
    eProsima_user_DllExport void tc_receiver_id(
            const std::string& _tc_receiver_id)
    {
        m_tc_receiver_id = _tc_receiver_id;
    }

    /*!
     * @brief This function moves the value in member tc_receiver_id
     * @param _tc_receiver_id New value to be moved in member tc_receiver_id
     */
    eProsima_user_DllExport void tc_receiver_id(
            std::string&& _tc_receiver_id)
    {
        m_tc_receiver_id = std::move(_tc_receiver_id);
    }

    /*!
     * @brief This function returns a constant reference to member tc_receiver_id
     * @return Constant reference to member tc_receiver_id
     */
    eProsima_user_DllExport const std::string& tc_receiver_id() const
    {
        return m_tc_receiver_id;
    }

    /*!
     * @brief This function returns a reference to member tc_receiver_id
     * @return Reference to member tc_receiver_id
     */
    eProsima_user_DllExport std::string& tc_receiver_id()
    {
        return m_tc_receiver_id;
    }


    /*!
     * @brief This function copies the value in member tc_assignment_command
     * @param _tc_assignment_command New value to be copied in member tc_assignment_command
     */
    eProsima_user_DllExport void tc_assignment_command(
            const std::string& _tc_assignment_command)
    {
        m_tc_assignment_command = _tc_assignment_command;
    }

    /*!
     * @brief This function moves the value in member tc_assignment_command
     * @param _tc_assignment_command New value to be moved in member tc_assignment_command
     */
    eProsima_user_DllExport void tc_assignment_command(
            std::string&& _tc_assignment_command)
    {
        m_tc_assignment_command = std::move(_tc_assignment_command);
    }

    /*!
     * @brief This function returns a constant reference to member tc_assignment_command
     * @return Constant reference to member tc_assignment_command
     */
    eProsima_user_DllExport const std::string& tc_assignment_command() const
    {
        return m_tc_assignment_command;
    }

    /*!
     * @brief This function returns a reference to member tc_assignment_command
     * @return Reference to member tc_assignment_command
     */
    eProsima_user_DllExport std::string& tc_assignment_command()
    {
        return m_tc_assignment_command;
    }


    /*!
     * @brief This function sets a value in member tc_assignment_loc_latitude
     * @param _tc_assignment_loc_latitude New value for member tc_assignment_loc_latitude
     */
    eProsima_user_DllExport void tc_assignment_loc_latitude(
            double _tc_assignment_loc_latitude)
    {
        m_tc_assignment_loc_latitude = _tc_assignment_loc_latitude;
    }

    /*!
     * @brief This function returns the value of member tc_assignment_loc_latitude
     * @return Value of member tc_assignment_loc_latitude
     */
    eProsima_user_DllExport double tc_assignment_loc_latitude() const
    {
        return m_tc_assignment_loc_latitude;
    }

    /*!
     * @brief This function returns a reference to member tc_assignment_loc_latitude
     * @return Reference to member tc_assignment_loc_latitude
     */
    eProsima_user_DllExport double& tc_assignment_loc_latitude()
    {
        return m_tc_assignment_loc_latitude;
    }


    /*!
     * @brief This function sets a value in member tc_assignment_loc_longitude
     * @param _tc_assignment_loc_longitude New value for member tc_assignment_loc_longitude
     */
    eProsima_user_DllExport void tc_assignment_loc_longitude(
            double _tc_assignment_loc_longitude)
    {
        m_tc_assignment_loc_longitude = _tc_assignment_loc_longitude;
    }

    /*!
     * @brief This function returns the value of member tc_assignment_loc_longitude
     * @return Value of member tc_assignment_loc_longitude
     */
    eProsima_user_DllExport double tc_assignment_loc_longitude() const
    {
        return m_tc_assignment_loc_longitude;
    }

    /*!
     * @brief This function returns a reference to member tc_assignment_loc_longitude
     * @return Reference to member tc_assignment_loc_longitude
     */
    eProsima_user_DllExport double& tc_assignment_loc_longitude()
    {
        return m_tc_assignment_loc_longitude;
    }


    /*!
     * @brief This function sets a value in member tc_assignment_loc_altitude
     * @param _tc_assignment_loc_altitude New value for member tc_assignment_loc_altitude
     */
    eProsima_user_DllExport void tc_assignment_loc_altitude(
            float _tc_assignment_loc_altitude)
    {
        m_tc_assignment_loc_altitude = _tc_assignment_loc_altitude;
    }

    /*!
     * @brief This function returns the value of member tc_assignment_loc_altitude
     * @return Value of member tc_assignment_loc_altitude
     */
    eProsima_user_DllExport float tc_assignment_loc_altitude() const
    {
        return m_tc_assignment_loc_altitude;
    }

    /*!
     * @brief This function returns a reference to member tc_assignment_loc_altitude
     * @return Reference to member tc_assignment_loc_altitude
     */
    eProsima_user_DllExport float& tc_assignment_loc_altitude()
    {
        return m_tc_assignment_loc_altitude;
    }


    /*!
     * @brief This function sets a value in member tc_assignment_loc_time_seconds
     * @param _tc_assignment_loc_time_seconds New value for member tc_assignment_loc_time_seconds
     */
    eProsima_user_DllExport void tc_assignment_loc_time_seconds(
            int32_t _tc_assignment_loc_time_seconds)
    {
        m_tc_assignment_loc_time_seconds = _tc_assignment_loc_time_seconds;
    }

    /*!
     * @brief This function returns the value of member tc_assignment_loc_time_seconds
     * @return Value of member tc_assignment_loc_time_seconds
     */
    eProsima_user_DllExport int32_t tc_assignment_loc_time_seconds() const
    {
        return m_tc_assignment_loc_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member tc_assignment_loc_time_seconds
     * @return Reference to member tc_assignment_loc_time_seconds
     */
    eProsima_user_DllExport int32_t& tc_assignment_loc_time_seconds()
    {
        return m_tc_assignment_loc_time_seconds;
    }


    /*!
     * @brief This function sets a value in member tc_assignment_loc_time_nano_seconds
     * @param _tc_assignment_loc_time_nano_seconds New value for member tc_assignment_loc_time_nano_seconds
     */
    eProsima_user_DllExport void tc_assignment_loc_time_nano_seconds(
            uint32_t _tc_assignment_loc_time_nano_seconds)
    {
        m_tc_assignment_loc_time_nano_seconds = _tc_assignment_loc_time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member tc_assignment_loc_time_nano_seconds
     * @return Value of member tc_assignment_loc_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t tc_assignment_loc_time_nano_seconds() const
    {
        return m_tc_assignment_loc_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member tc_assignment_loc_time_nano_seconds
     * @return Reference to member tc_assignment_loc_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& tc_assignment_loc_time_nano_seconds()
    {
        return m_tc_assignment_loc_time_nano_seconds;
    }


    /*!
     * @brief This function sets a value in member tc_assignment_loc_speed_mps
     * @param _tc_assignment_loc_speed_mps New value for member tc_assignment_loc_speed_mps
     */
    eProsima_user_DllExport void tc_assignment_loc_speed_mps(
            float _tc_assignment_loc_speed_mps)
    {
        m_tc_assignment_loc_speed_mps = _tc_assignment_loc_speed_mps;
    }

    /*!
     * @brief This function returns the value of member tc_assignment_loc_speed_mps
     * @return Value of member tc_assignment_loc_speed_mps
     */
    eProsima_user_DllExport float tc_assignment_loc_speed_mps() const
    {
        return m_tc_assignment_loc_speed_mps;
    }

    /*!
     * @brief This function returns a reference to member tc_assignment_loc_speed_mps
     * @return Reference to member tc_assignment_loc_speed_mps
     */
    eProsima_user_DllExport float& tc_assignment_loc_speed_mps()
    {
        return m_tc_assignment_loc_speed_mps;
    }


    /*!
     * @brief This function sets a value in member tc_assignment_loc_orientation_degrees
     * @param _tc_assignment_loc_orientation_degrees New value for member tc_assignment_loc_orientation_degrees
     */
    eProsima_user_DllExport void tc_assignment_loc_orientation_degrees(
            int16_t _tc_assignment_loc_orientation_degrees)
    {
        m_tc_assignment_loc_orientation_degrees = _tc_assignment_loc_orientation_degrees;
    }

    /*!
     * @brief This function returns the value of member tc_assignment_loc_orientation_degrees
     * @return Value of member tc_assignment_loc_orientation_degrees
     */
    eProsima_user_DllExport int16_t tc_assignment_loc_orientation_degrees() const
    {
        return m_tc_assignment_loc_orientation_degrees;
    }

    /*!
     * @brief This function returns a reference to member tc_assignment_loc_orientation_degrees
     * @return Reference to member tc_assignment_loc_orientation_degrees
     */
    eProsima_user_DllExport int16_t& tc_assignment_loc_orientation_degrees()
    {
        return m_tc_assignment_loc_orientation_degrees;
    }



private:

    int16_t m_message_type{0};
    std::string m_sr_header_sender_id;
    int32_t m_sr_header_time_seconds{0};
    uint32_t m_sr_header_time_nano_seconds{0};
    double m_sr_location_latitude{0.0};
    double m_sr_location_longitude{0.0};
    float m_sr_location_altitude{0.0};
    int32_t m_sr_location_time_seconds{0};
    uint32_t m_sr_location_time_nano_seconds{0};
    float m_sr_location_speed_mps{0.0};
    int16_t m_sr_location_orientation_degrees{0};
    int16_t m_sr_status_task_status{0};
    uint16_t m_sr_status_battery_percentage{0};
    float m_sr_status_signal_strength_dbm{0.0};
    bool m_sr_status_system_error{false};
    std::string m_cd_header_sender_id;
    int32_t m_cd_header_time_seconds{0};
    uint32_t m_cd_header_time_nano_seconds{0};
    std::string m_cd_detection_target_ID;
    int16_t m_cd_detection_target_type{0};
    double m_cd_detection_loc_latitude{0.0};
    double m_cd_detection_loc_longitude{0.0};
    float m_cd_detection_loc_altitude{0.0};
    int32_t m_cd_detection_loc_time_seconds{0};
    uint32_t m_cd_detection_loc_time_nano_seconds{0};
    float m_cd_detection_loc_speed_mps{0.0};
    int16_t m_cd_detection_loc_orientation_degrees{0};
    float m_cd_detection_confidence_level{0.0};
    std::string m_cd_detection_description;
    std::string m_cd_detection_raw_data_link;
    std::string m_tc_header_sender_id;
    int32_t m_tc_header_time_seconds{0};
    uint32_t m_tc_header_time_nano_seconds{0};
    std::string m_tc_receiver_id;
    std::string m_tc_assignment_command;
    double m_tc_assignment_loc_latitude{0.0};
    double m_tc_assignment_loc_longitude{0.0};
    float m_tc_assignment_loc_altitude{0.0};
    int32_t m_tc_assignment_loc_time_seconds{0};
    uint32_t m_tc_assignment_loc_time_nano_seconds{0};
    float m_tc_assignment_loc_speed_mps{0.0};
    int16_t m_tc_assignment_loc_orientation_degrees{0};

};

} // namespace Messaging

#endif // _FAST_DDS_GENERATED_MESSAGİNG_MESSAGİNG_HPP_


