// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Intelligence.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__INTELLİGENCE_INTELLİGENCE_HPP
#define FAST_DDS_GENERATED__INTELLİGENCE_INTELLİGENCE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(INTELLİGENCE_SOURCE)
#define INTELLİGENCE_DllAPI __declspec( dllexport )
#else
#define INTELLİGENCE_DllAPI __declspec( dllimport )
#endif // INTELLİGENCE_SOURCE
#else
#define INTELLİGENCE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define INTELLİGENCE_DllAPI
#endif // _WIN32

namespace Intelligence {

/*!
 * @brief This class represents the structure FlatIntelligence defined by the user in the IDL file.
 * @ingroup Intelligence
 */
class FlatIntelligence
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport FlatIntelligence()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~FlatIntelligence()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object FlatIntelligence that will be copied.
     */
    eProsima_user_DllExport FlatIntelligence(
            const FlatIntelligence& x)
    {
                    m_vs_task_status = x.m_vs_task_status;

                    m_vs_battery_percentage = x.m_vs_battery_percentage;

                    m_vs_signal_strength_dbm = x.m_vs_signal_strength_dbm;

                    m_vs_system_error = x.m_vs_system_error;

                    m_td_target_ID = x.m_td_target_ID;

                    m_td_target_type = x.m_td_target_type;

                    m_td_location_latitude = x.m_td_location_latitude;

                    m_td_location_longitude = x.m_td_location_longitude;

                    m_td_location_altitude = x.m_td_location_altitude;

                    m_td_location_time_seconds = x.m_td_location_time_seconds;

                    m_td_location_time_nano_seconds = x.m_td_location_time_nano_seconds;

                    m_td_location_speed_mps = x.m_td_location_speed_mps;

                    m_td_location_orientation_degrees = x.m_td_location_orientation_degrees;

                    m_td_confidence_level = x.m_td_confidence_level;

                    m_td_description = x.m_td_description;

                    m_td_raw_data_link = x.m_td_raw_data_link;

                    m_ta_command = x.m_ta_command;

                    m_ta_location_latitude = x.m_ta_location_latitude;

                    m_ta_location_longitude = x.m_ta_location_longitude;

                    m_ta_location_altitude = x.m_ta_location_altitude;

                    m_ta_location_time_seconds = x.m_ta_location_time_seconds;

                    m_ta_location_time_nano_seconds = x.m_ta_location_time_nano_seconds;

                    m_ta_location_speed_mps = x.m_ta_location_speed_mps;

                    m_ta_location_orientation_degrees = x.m_ta_location_orientation_degrees;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object FlatIntelligence that will be copied.
     */
    eProsima_user_DllExport FlatIntelligence(
            FlatIntelligence&& x) noexcept
    {
        m_vs_task_status = x.m_vs_task_status;
        m_vs_battery_percentage = x.m_vs_battery_percentage;
        m_vs_signal_strength_dbm = x.m_vs_signal_strength_dbm;
        m_vs_system_error = x.m_vs_system_error;
        m_td_target_ID = std::move(x.m_td_target_ID);
        m_td_target_type = x.m_td_target_type;
        m_td_location_latitude = x.m_td_location_latitude;
        m_td_location_longitude = x.m_td_location_longitude;
        m_td_location_altitude = x.m_td_location_altitude;
        m_td_location_time_seconds = x.m_td_location_time_seconds;
        m_td_location_time_nano_seconds = x.m_td_location_time_nano_seconds;
        m_td_location_speed_mps = x.m_td_location_speed_mps;
        m_td_location_orientation_degrees = x.m_td_location_orientation_degrees;
        m_td_confidence_level = x.m_td_confidence_level;
        m_td_description = std::move(x.m_td_description);
        m_td_raw_data_link = std::move(x.m_td_raw_data_link);
        m_ta_command = std::move(x.m_ta_command);
        m_ta_location_latitude = x.m_ta_location_latitude;
        m_ta_location_longitude = x.m_ta_location_longitude;
        m_ta_location_altitude = x.m_ta_location_altitude;
        m_ta_location_time_seconds = x.m_ta_location_time_seconds;
        m_ta_location_time_nano_seconds = x.m_ta_location_time_nano_seconds;
        m_ta_location_speed_mps = x.m_ta_location_speed_mps;
        m_ta_location_orientation_degrees = x.m_ta_location_orientation_degrees;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object FlatIntelligence that will be copied.
     */
    eProsima_user_DllExport FlatIntelligence& operator =(
            const FlatIntelligence& x)
    {

                    m_vs_task_status = x.m_vs_task_status;

                    m_vs_battery_percentage = x.m_vs_battery_percentage;

                    m_vs_signal_strength_dbm = x.m_vs_signal_strength_dbm;

                    m_vs_system_error = x.m_vs_system_error;

                    m_td_target_ID = x.m_td_target_ID;

                    m_td_target_type = x.m_td_target_type;

                    m_td_location_latitude = x.m_td_location_latitude;

                    m_td_location_longitude = x.m_td_location_longitude;

                    m_td_location_altitude = x.m_td_location_altitude;

                    m_td_location_time_seconds = x.m_td_location_time_seconds;

                    m_td_location_time_nano_seconds = x.m_td_location_time_nano_seconds;

                    m_td_location_speed_mps = x.m_td_location_speed_mps;

                    m_td_location_orientation_degrees = x.m_td_location_orientation_degrees;

                    m_td_confidence_level = x.m_td_confidence_level;

                    m_td_description = x.m_td_description;

                    m_td_raw_data_link = x.m_td_raw_data_link;

                    m_ta_command = x.m_ta_command;

                    m_ta_location_latitude = x.m_ta_location_latitude;

                    m_ta_location_longitude = x.m_ta_location_longitude;

                    m_ta_location_altitude = x.m_ta_location_altitude;

                    m_ta_location_time_seconds = x.m_ta_location_time_seconds;

                    m_ta_location_time_nano_seconds = x.m_ta_location_time_nano_seconds;

                    m_ta_location_speed_mps = x.m_ta_location_speed_mps;

                    m_ta_location_orientation_degrees = x.m_ta_location_orientation_degrees;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object FlatIntelligence that will be copied.
     */
    eProsima_user_DllExport FlatIntelligence& operator =(
            FlatIntelligence&& x) noexcept
    {

        m_vs_task_status = x.m_vs_task_status;
        m_vs_battery_percentage = x.m_vs_battery_percentage;
        m_vs_signal_strength_dbm = x.m_vs_signal_strength_dbm;
        m_vs_system_error = x.m_vs_system_error;
        m_td_target_ID = std::move(x.m_td_target_ID);
        m_td_target_type = x.m_td_target_type;
        m_td_location_latitude = x.m_td_location_latitude;
        m_td_location_longitude = x.m_td_location_longitude;
        m_td_location_altitude = x.m_td_location_altitude;
        m_td_location_time_seconds = x.m_td_location_time_seconds;
        m_td_location_time_nano_seconds = x.m_td_location_time_nano_seconds;
        m_td_location_speed_mps = x.m_td_location_speed_mps;
        m_td_location_orientation_degrees = x.m_td_location_orientation_degrees;
        m_td_confidence_level = x.m_td_confidence_level;
        m_td_description = std::move(x.m_td_description);
        m_td_raw_data_link = std::move(x.m_td_raw_data_link);
        m_ta_command = std::move(x.m_ta_command);
        m_ta_location_latitude = x.m_ta_location_latitude;
        m_ta_location_longitude = x.m_ta_location_longitude;
        m_ta_location_altitude = x.m_ta_location_altitude;
        m_ta_location_time_seconds = x.m_ta_location_time_seconds;
        m_ta_location_time_nano_seconds = x.m_ta_location_time_nano_seconds;
        m_ta_location_speed_mps = x.m_ta_location_speed_mps;
        m_ta_location_orientation_degrees = x.m_ta_location_orientation_degrees;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x FlatIntelligence object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const FlatIntelligence& x) const
    {
        return (m_vs_task_status == x.m_vs_task_status &&
           m_vs_battery_percentage == x.m_vs_battery_percentage &&
           m_vs_signal_strength_dbm == x.m_vs_signal_strength_dbm &&
           m_vs_system_error == x.m_vs_system_error &&
           m_td_target_ID == x.m_td_target_ID &&
           m_td_target_type == x.m_td_target_type &&
           m_td_location_latitude == x.m_td_location_latitude &&
           m_td_location_longitude == x.m_td_location_longitude &&
           m_td_location_altitude == x.m_td_location_altitude &&
           m_td_location_time_seconds == x.m_td_location_time_seconds &&
           m_td_location_time_nano_seconds == x.m_td_location_time_nano_seconds &&
           m_td_location_speed_mps == x.m_td_location_speed_mps &&
           m_td_location_orientation_degrees == x.m_td_location_orientation_degrees &&
           m_td_confidence_level == x.m_td_confidence_level &&
           m_td_description == x.m_td_description &&
           m_td_raw_data_link == x.m_td_raw_data_link &&
           m_ta_command == x.m_ta_command &&
           m_ta_location_latitude == x.m_ta_location_latitude &&
           m_ta_location_longitude == x.m_ta_location_longitude &&
           m_ta_location_altitude == x.m_ta_location_altitude &&
           m_ta_location_time_seconds == x.m_ta_location_time_seconds &&
           m_ta_location_time_nano_seconds == x.m_ta_location_time_nano_seconds &&
           m_ta_location_speed_mps == x.m_ta_location_speed_mps &&
           m_ta_location_orientation_degrees == x.m_ta_location_orientation_degrees);
    }

    /*!
     * @brief Comparison operator.
     * @param x FlatIntelligence object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const FlatIntelligence& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member vs_task_status
     * @param _vs_task_status New value for member vs_task_status
     */
    eProsima_user_DllExport void vs_task_status(
            int16_t _vs_task_status)
    {
        m_vs_task_status = _vs_task_status;
    }

    /*!
     * @brief This function returns the value of member vs_task_status
     * @return Value of member vs_task_status
     */
    eProsima_user_DllExport int16_t vs_task_status() const
    {
        return m_vs_task_status;
    }

    /*!
     * @brief This function returns a reference to member vs_task_status
     * @return Reference to member vs_task_status
     */
    eProsima_user_DllExport int16_t& vs_task_status()
    {
        return m_vs_task_status;
    }


    /*!
     * @brief This function sets a value in member vs_battery_percentage
     * @param _vs_battery_percentage New value for member vs_battery_percentage
     */
    eProsima_user_DllExport void vs_battery_percentage(
            uint16_t _vs_battery_percentage)
    {
        m_vs_battery_percentage = _vs_battery_percentage;
    }

    /*!
     * @brief This function returns the value of member vs_battery_percentage
     * @return Value of member vs_battery_percentage
     */
    eProsima_user_DllExport uint16_t vs_battery_percentage() const
    {
        return m_vs_battery_percentage;
    }

    /*!
     * @brief This function returns a reference to member vs_battery_percentage
     * @return Reference to member vs_battery_percentage
     */
    eProsima_user_DllExport uint16_t& vs_battery_percentage()
    {
        return m_vs_battery_percentage;
    }


    /*!
     * @brief This function sets a value in member vs_signal_strength_dbm
     * @param _vs_signal_strength_dbm New value for member vs_signal_strength_dbm
     */
    eProsima_user_DllExport void vs_signal_strength_dbm(
            float _vs_signal_strength_dbm)
    {
        m_vs_signal_strength_dbm = _vs_signal_strength_dbm;
    }

    /*!
     * @brief This function returns the value of member vs_signal_strength_dbm
     * @return Value of member vs_signal_strength_dbm
     */
    eProsima_user_DllExport float vs_signal_strength_dbm() const
    {
        return m_vs_signal_strength_dbm;
    }

    /*!
     * @brief This function returns a reference to member vs_signal_strength_dbm
     * @return Reference to member vs_signal_strength_dbm
     */
    eProsima_user_DllExport float& vs_signal_strength_dbm()
    {
        return m_vs_signal_strength_dbm;
    }


    /*!
     * @brief This function sets a value in member vs_system_error
     * @param _vs_system_error New value for member vs_system_error
     */
    eProsima_user_DllExport void vs_system_error(
            bool _vs_system_error)
    {
        m_vs_system_error = _vs_system_error;
    }

    /*!
     * @brief This function returns the value of member vs_system_error
     * @return Value of member vs_system_error
     */
    eProsima_user_DllExport bool vs_system_error() const
    {
        return m_vs_system_error;
    }

    /*!
     * @brief This function returns a reference to member vs_system_error
     * @return Reference to member vs_system_error
     */
    eProsima_user_DllExport bool& vs_system_error()
    {
        return m_vs_system_error;
    }


    /*!
     * @brief This function copies the value in member td_target_ID
     * @param _td_target_ID New value to be copied in member td_target_ID
     */
    eProsima_user_DllExport void td_target_ID(
            const std::string& _td_target_ID)
    {
        m_td_target_ID = _td_target_ID;
    }

    /*!
     * @brief This function moves the value in member td_target_ID
     * @param _td_target_ID New value to be moved in member td_target_ID
     */
    eProsima_user_DllExport void td_target_ID(
            std::string&& _td_target_ID)
    {
        m_td_target_ID = std::move(_td_target_ID);
    }

    /*!
     * @brief This function returns a constant reference to member td_target_ID
     * @return Constant reference to member td_target_ID
     */
    eProsima_user_DllExport const std::string& td_target_ID() const
    {
        return m_td_target_ID;
    }

    /*!
     * @brief This function returns a reference to member td_target_ID
     * @return Reference to member td_target_ID
     */
    eProsima_user_DllExport std::string& td_target_ID()
    {
        return m_td_target_ID;
    }


    /*!
     * @brief This function sets a value in member td_target_type
     * @param _td_target_type New value for member td_target_type
     */
    eProsima_user_DllExport void td_target_type(
            int16_t _td_target_type)
    {
        m_td_target_type = _td_target_type;
    }

    /*!
     * @brief This function returns the value of member td_target_type
     * @return Value of member td_target_type
     */
    eProsima_user_DllExport int16_t td_target_type() const
    {
        return m_td_target_type;
    }

    /*!
     * @brief This function returns a reference to member td_target_type
     * @return Reference to member td_target_type
     */
    eProsima_user_DllExport int16_t& td_target_type()
    {
        return m_td_target_type;
    }


    /*!
     * @brief This function sets a value in member td_location_latitude
     * @param _td_location_latitude New value for member td_location_latitude
     */
    eProsima_user_DllExport void td_location_latitude(
            double _td_location_latitude)
    {
        m_td_location_latitude = _td_location_latitude;
    }

    /*!
     * @brief This function returns the value of member td_location_latitude
     * @return Value of member td_location_latitude
     */
    eProsima_user_DllExport double td_location_latitude() const
    {
        return m_td_location_latitude;
    }

    /*!
     * @brief This function returns a reference to member td_location_latitude
     * @return Reference to member td_location_latitude
     */
    eProsima_user_DllExport double& td_location_latitude()
    {
        return m_td_location_latitude;
    }


    /*!
     * @brief This function sets a value in member td_location_longitude
     * @param _td_location_longitude New value for member td_location_longitude
     */
    eProsima_user_DllExport void td_location_longitude(
            double _td_location_longitude)
    {
        m_td_location_longitude = _td_location_longitude;
    }

    /*!
     * @brief This function returns the value of member td_location_longitude
     * @return Value of member td_location_longitude
     */
    eProsima_user_DllExport double td_location_longitude() const
    {
        return m_td_location_longitude;
    }

    /*!
     * @brief This function returns a reference to member td_location_longitude
     * @return Reference to member td_location_longitude
     */
    eProsima_user_DllExport double& td_location_longitude()
    {
        return m_td_location_longitude;
    }


    /*!
     * @brief This function sets a value in member td_location_altitude
     * @param _td_location_altitude New value for member td_location_altitude
     */
    eProsima_user_DllExport void td_location_altitude(
            float _td_location_altitude)
    {
        m_td_location_altitude = _td_location_altitude;
    }

    /*!
     * @brief This function returns the value of member td_location_altitude
     * @return Value of member td_location_altitude
     */
    eProsima_user_DllExport float td_location_altitude() const
    {
        return m_td_location_altitude;
    }

    /*!
     * @brief This function returns a reference to member td_location_altitude
     * @return Reference to member td_location_altitude
     */
    eProsima_user_DllExport float& td_location_altitude()
    {
        return m_td_location_altitude;
    }


    /*!
     * @brief This function sets a value in member td_location_time_seconds
     * @param _td_location_time_seconds New value for member td_location_time_seconds
     */
    eProsima_user_DllExport void td_location_time_seconds(
            int32_t _td_location_time_seconds)
    {
        m_td_location_time_seconds = _td_location_time_seconds;
    }

    /*!
     * @brief This function returns the value of member td_location_time_seconds
     * @return Value of member td_location_time_seconds
     */
    eProsima_user_DllExport int32_t td_location_time_seconds() const
    {
        return m_td_location_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member td_location_time_seconds
     * @return Reference to member td_location_time_seconds
     */
    eProsima_user_DllExport int32_t& td_location_time_seconds()
    {
        return m_td_location_time_seconds;
    }


    /*!
     * @brief This function sets a value in member td_location_time_nano_seconds
     * @param _td_location_time_nano_seconds New value for member td_location_time_nano_seconds
     */
    eProsima_user_DllExport void td_location_time_nano_seconds(
            uint32_t _td_location_time_nano_seconds)
    {
        m_td_location_time_nano_seconds = _td_location_time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member td_location_time_nano_seconds
     * @return Value of member td_location_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t td_location_time_nano_seconds() const
    {
        return m_td_location_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member td_location_time_nano_seconds
     * @return Reference to member td_location_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& td_location_time_nano_seconds()
    {
        return m_td_location_time_nano_seconds;
    }


    /*!
     * @brief This function sets a value in member td_location_speed_mps
     * @param _td_location_speed_mps New value for member td_location_speed_mps
     */
    eProsima_user_DllExport void td_location_speed_mps(
            float _td_location_speed_mps)
    {
        m_td_location_speed_mps = _td_location_speed_mps;
    }

    /*!
     * @brief This function returns the value of member td_location_speed_mps
     * @return Value of member td_location_speed_mps
     */
    eProsima_user_DllExport float td_location_speed_mps() const
    {
        return m_td_location_speed_mps;
    }

    /*!
     * @brief This function returns a reference to member td_location_speed_mps
     * @return Reference to member td_location_speed_mps
     */
    eProsima_user_DllExport float& td_location_speed_mps()
    {
        return m_td_location_speed_mps;
    }


    /*!
     * @brief This function sets a value in member td_location_orientation_degrees
     * @param _td_location_orientation_degrees New value for member td_location_orientation_degrees
     */
    eProsima_user_DllExport void td_location_orientation_degrees(
            int16_t _td_location_orientation_degrees)
    {
        m_td_location_orientation_degrees = _td_location_orientation_degrees;
    }

    /*!
     * @brief This function returns the value of member td_location_orientation_degrees
     * @return Value of member td_location_orientation_degrees
     */
    eProsima_user_DllExport int16_t td_location_orientation_degrees() const
    {
        return m_td_location_orientation_degrees;
    }

    /*!
     * @brief This function returns a reference to member td_location_orientation_degrees
     * @return Reference to member td_location_orientation_degrees
     */
    eProsima_user_DllExport int16_t& td_location_orientation_degrees()
    {
        return m_td_location_orientation_degrees;
    }


    /*!
     * @brief This function sets a value in member td_confidence_level
     * @param _td_confidence_level New value for member td_confidence_level
     */
    eProsima_user_DllExport void td_confidence_level(
            float _td_confidence_level)
    {
        m_td_confidence_level = _td_confidence_level;
    }

    /*!
     * @brief This function returns the value of member td_confidence_level
     * @return Value of member td_confidence_level
     */
    eProsima_user_DllExport float td_confidence_level() const
    {
        return m_td_confidence_level;
    }

    /*!
     * @brief This function returns a reference to member td_confidence_level
     * @return Reference to member td_confidence_level
     */
    eProsima_user_DllExport float& td_confidence_level()
    {
        return m_td_confidence_level;
    }


    /*!
     * @brief This function copies the value in member td_description
     * @param _td_description New value to be copied in member td_description
     */
    eProsima_user_DllExport void td_description(
            const std::string& _td_description)
    {
        m_td_description = _td_description;
    }

    /*!
     * @brief This function moves the value in member td_description
     * @param _td_description New value to be moved in member td_description
     */
    eProsima_user_DllExport void td_description(
            std::string&& _td_description)
    {
        m_td_description = std::move(_td_description);
    }

    /*!
     * @brief This function returns a constant reference to member td_description
     * @return Constant reference to member td_description
     */
    eProsima_user_DllExport const std::string& td_description() const
    {
        return m_td_description;
    }

    /*!
     * @brief This function returns a reference to member td_description
     * @return Reference to member td_description
     */
    eProsima_user_DllExport std::string& td_description()
    {
        return m_td_description;
    }


    /*!
     * @brief This function copies the value in member td_raw_data_link
     * @param _td_raw_data_link New value to be copied in member td_raw_data_link
     */
    eProsima_user_DllExport void td_raw_data_link(
            const std::string& _td_raw_data_link)
    {
        m_td_raw_data_link = _td_raw_data_link;
    }

    /*!
     * @brief This function moves the value in member td_raw_data_link
     * @param _td_raw_data_link New value to be moved in member td_raw_data_link
     */
    eProsima_user_DllExport void td_raw_data_link(
            std::string&& _td_raw_data_link)
    {
        m_td_raw_data_link = std::move(_td_raw_data_link);
    }

    /*!
     * @brief This function returns a constant reference to member td_raw_data_link
     * @return Constant reference to member td_raw_data_link
     */
    eProsima_user_DllExport const std::string& td_raw_data_link() const
    {
        return m_td_raw_data_link;
    }

    /*!
     * @brief This function returns a reference to member td_raw_data_link
     * @return Reference to member td_raw_data_link
     */
    eProsima_user_DllExport std::string& td_raw_data_link()
    {
        return m_td_raw_data_link;
    }


    /*!
     * @brief This function copies the value in member ta_command
     * @param _ta_command New value to be copied in member ta_command
     */
    eProsima_user_DllExport void ta_command(
            const std::string& _ta_command)
    {
        m_ta_command = _ta_command;
    }

    /*!
     * @brief This function moves the value in member ta_command
     * @param _ta_command New value to be moved in member ta_command
     */
    eProsima_user_DllExport void ta_command(
            std::string&& _ta_command)
    {
        m_ta_command = std::move(_ta_command);
    }

    /*!
     * @brief This function returns a constant reference to member ta_command
     * @return Constant reference to member ta_command
     */
    eProsima_user_DllExport const std::string& ta_command() const
    {
        return m_ta_command;
    }

    /*!
     * @brief This function returns a reference to member ta_command
     * @return Reference to member ta_command
     */
    eProsima_user_DllExport std::string& ta_command()
    {
        return m_ta_command;
    }


    /*!
     * @brief This function sets a value in member ta_location_latitude
     * @param _ta_location_latitude New value for member ta_location_latitude
     */
    eProsima_user_DllExport void ta_location_latitude(
            double _ta_location_latitude)
    {
        m_ta_location_latitude = _ta_location_latitude;
    }

    /*!
     * @brief This function returns the value of member ta_location_latitude
     * @return Value of member ta_location_latitude
     */
    eProsima_user_DllExport double ta_location_latitude() const
    {
        return m_ta_location_latitude;
    }

    /*!
     * @brief This function returns a reference to member ta_location_latitude
     * @return Reference to member ta_location_latitude
     */
    eProsima_user_DllExport double& ta_location_latitude()
    {
        return m_ta_location_latitude;
    }


    /*!
     * @brief This function sets a value in member ta_location_longitude
     * @param _ta_location_longitude New value for member ta_location_longitude
     */
    eProsima_user_DllExport void ta_location_longitude(
            double _ta_location_longitude)
    {
        m_ta_location_longitude = _ta_location_longitude;
    }

    /*!
     * @brief This function returns the value of member ta_location_longitude
     * @return Value of member ta_location_longitude
     */
    eProsima_user_DllExport double ta_location_longitude() const
    {
        return m_ta_location_longitude;
    }

    /*!
     * @brief This function returns a reference to member ta_location_longitude
     * @return Reference to member ta_location_longitude
     */
    eProsima_user_DllExport double& ta_location_longitude()
    {
        return m_ta_location_longitude;
    }


    /*!
     * @brief This function sets a value in member ta_location_altitude
     * @param _ta_location_altitude New value for member ta_location_altitude
     */
    eProsima_user_DllExport void ta_location_altitude(
            float _ta_location_altitude)
    {
        m_ta_location_altitude = _ta_location_altitude;
    }

    /*!
     * @brief This function returns the value of member ta_location_altitude
     * @return Value of member ta_location_altitude
     */
    eProsima_user_DllExport float ta_location_altitude() const
    {
        return m_ta_location_altitude;
    }

    /*!
     * @brief This function returns a reference to member ta_location_altitude
     * @return Reference to member ta_location_altitude
     */
    eProsima_user_DllExport float& ta_location_altitude()
    {
        return m_ta_location_altitude;
    }


    /*!
     * @brief This function sets a value in member ta_location_time_seconds
     * @param _ta_location_time_seconds New value for member ta_location_time_seconds
     */
    eProsima_user_DllExport void ta_location_time_seconds(
            int32_t _ta_location_time_seconds)
    {
        m_ta_location_time_seconds = _ta_location_time_seconds;
    }

    /*!
     * @brief This function returns the value of member ta_location_time_seconds
     * @return Value of member ta_location_time_seconds
     */
    eProsima_user_DllExport int32_t ta_location_time_seconds() const
    {
        return m_ta_location_time_seconds;
    }

    /*!
     * @brief This function returns a reference to member ta_location_time_seconds
     * @return Reference to member ta_location_time_seconds
     */
    eProsima_user_DllExport int32_t& ta_location_time_seconds()
    {
        return m_ta_location_time_seconds;
    }


    /*!
     * @brief This function sets a value in member ta_location_time_nano_seconds
     * @param _ta_location_time_nano_seconds New value for member ta_location_time_nano_seconds
     */
    eProsima_user_DllExport void ta_location_time_nano_seconds(
            uint32_t _ta_location_time_nano_seconds)
    {
        m_ta_location_time_nano_seconds = _ta_location_time_nano_seconds;
    }

    /*!
     * @brief This function returns the value of member ta_location_time_nano_seconds
     * @return Value of member ta_location_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t ta_location_time_nano_seconds() const
    {
        return m_ta_location_time_nano_seconds;
    }

    /*!
     * @brief This function returns a reference to member ta_location_time_nano_seconds
     * @return Reference to member ta_location_time_nano_seconds
     */
    eProsima_user_DllExport uint32_t& ta_location_time_nano_seconds()
    {
        return m_ta_location_time_nano_seconds;
    }


    /*!
     * @brief This function sets a value in member ta_location_speed_mps
     * @param _ta_location_speed_mps New value for member ta_location_speed_mps
     */
    eProsima_user_DllExport void ta_location_speed_mps(
            float _ta_location_speed_mps)
    {
        m_ta_location_speed_mps = _ta_location_speed_mps;
    }

    /*!
     * @brief This function returns the value of member ta_location_speed_mps
     * @return Value of member ta_location_speed_mps
     */
    eProsima_user_DllExport float ta_location_speed_mps() const
    {
        return m_ta_location_speed_mps;
    }

    /*!
     * @brief This function returns a reference to member ta_location_speed_mps
     * @return Reference to member ta_location_speed_mps
     */
    eProsima_user_DllExport float& ta_location_speed_mps()
    {
        return m_ta_location_speed_mps;
    }


    /*!
     * @brief This function sets a value in member ta_location_orientation_degrees
     * @param _ta_location_orientation_degrees New value for member ta_location_orientation_degrees
     */
    eProsima_user_DllExport void ta_location_orientation_degrees(
            int16_t _ta_location_orientation_degrees)
    {
        m_ta_location_orientation_degrees = _ta_location_orientation_degrees;
    }

    /*!
     * @brief This function returns the value of member ta_location_orientation_degrees
     * @return Value of member ta_location_orientation_degrees
     */
    eProsima_user_DllExport int16_t ta_location_orientation_degrees() const
    {
        return m_ta_location_orientation_degrees;
    }

    /*!
     * @brief This function returns a reference to member ta_location_orientation_degrees
     * @return Reference to member ta_location_orientation_degrees
     */
    eProsima_user_DllExport int16_t& ta_location_orientation_degrees()
    {
        return m_ta_location_orientation_degrees;
    }



private:

    int16_t m_vs_task_status{0};
    uint16_t m_vs_battery_percentage{0};
    float m_vs_signal_strength_dbm{0.0};
    bool m_vs_system_error{false};
    std::string m_td_target_ID;
    int16_t m_td_target_type{0};
    double m_td_location_latitude{0.0};
    double m_td_location_longitude{0.0};
    float m_td_location_altitude{0.0};
    int32_t m_td_location_time_seconds{0};
    uint32_t m_td_location_time_nano_seconds{0};
    float m_td_location_speed_mps{0.0};
    int16_t m_td_location_orientation_degrees{0};
    float m_td_confidence_level{0.0};
    std::string m_td_description;
    std::string m_td_raw_data_link;
    std::string m_ta_command;
    double m_ta_location_latitude{0.0};
    double m_ta_location_longitude{0.0};
    float m_ta_location_altitude{0.0};
    int32_t m_ta_location_time_seconds{0};
    uint32_t m_ta_location_time_nano_seconds{0};
    float m_ta_location_speed_mps{0.0};
    int16_t m_ta_location_orientation_degrees{0};

};

} // namespace Intelligence

#endif // _FAST_DDS_GENERATED_INTELLİGENCE_INTELLİGENCE_HPP_


