// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file IntelligenceTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "IntelligenceTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Intelligence.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace Intelligence {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_FlatIntelligence_type_identifier(
        TypeIdentifierPair& type_ids_FlatIntelligence)
{

    ReturnCode_t return_code_FlatIntelligence {eprosima::fastdds::dds::RETCODE_OK};
    return_code_FlatIntelligence =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Intelligence::FlatIntelligence", type_ids_FlatIntelligence);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_FlatIntelligence)
    {
        StructTypeFlag struct_flags_FlatIntelligence = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_FlatIntelligence = "Intelligence::FlatIntelligence";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_FlatIntelligence;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_FlatIntelligence;
        CompleteTypeDetail detail_FlatIntelligence = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_FlatIntelligence, ann_custom_FlatIntelligence, type_name_FlatIntelligence.to_string());
        CompleteStructHeader header_FlatIntelligence;
        header_FlatIntelligence = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_FlatIntelligence);
        CompleteStructMemberSeq member_seq_FlatIntelligence;
        {
            TypeIdentifierPair type_ids_vs_task_status;
            ReturnCode_t return_code_vs_task_status {eprosima::fastdds::dds::RETCODE_OK};
            return_code_vs_task_status =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int16_t", type_ids_vs_task_status);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_vs_task_status)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "vs_task_status Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_vs_task_status = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_vs_task_status = 0x00000000;
            bool common_vs_task_status_ec {false};
            CommonStructMember common_vs_task_status {TypeObjectUtils::build_common_struct_member(member_id_vs_task_status, member_flags_vs_task_status, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_vs_task_status, common_vs_task_status_ec))};
            if (!common_vs_task_status_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure vs_task_status member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_vs_task_status = "vs_task_status";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_vs_task_status;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_vs_task_status = TypeObjectUtils::build_complete_member_detail(name_vs_task_status, member_ann_builtin_vs_task_status, ann_custom_FlatIntelligence);
            CompleteStructMember member_vs_task_status = TypeObjectUtils::build_complete_struct_member(common_vs_task_status, detail_vs_task_status);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_vs_task_status);
        }
        {
            TypeIdentifierPair type_ids_vs_battery_percentage;
            ReturnCode_t return_code_vs_battery_percentage {eprosima::fastdds::dds::RETCODE_OK};
            return_code_vs_battery_percentage =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_vs_battery_percentage);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_vs_battery_percentage)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "vs_battery_percentage Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_vs_battery_percentage = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_vs_battery_percentage = 0x00000001;
            bool common_vs_battery_percentage_ec {false};
            CommonStructMember common_vs_battery_percentage {TypeObjectUtils::build_common_struct_member(member_id_vs_battery_percentage, member_flags_vs_battery_percentage, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_vs_battery_percentage, common_vs_battery_percentage_ec))};
            if (!common_vs_battery_percentage_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure vs_battery_percentage member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_vs_battery_percentage = "vs_battery_percentage";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_vs_battery_percentage;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_vs_battery_percentage = TypeObjectUtils::build_complete_member_detail(name_vs_battery_percentage, member_ann_builtin_vs_battery_percentage, ann_custom_FlatIntelligence);
            CompleteStructMember member_vs_battery_percentage = TypeObjectUtils::build_complete_struct_member(common_vs_battery_percentage, detail_vs_battery_percentage);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_vs_battery_percentage);
        }
        {
            TypeIdentifierPair type_ids_vs_signal_strength_dbm;
            ReturnCode_t return_code_vs_signal_strength_dbm {eprosima::fastdds::dds::RETCODE_OK};
            return_code_vs_signal_strength_dbm =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_vs_signal_strength_dbm);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_vs_signal_strength_dbm)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "vs_signal_strength_dbm Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_vs_signal_strength_dbm = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_vs_signal_strength_dbm = 0x00000002;
            bool common_vs_signal_strength_dbm_ec {false};
            CommonStructMember common_vs_signal_strength_dbm {TypeObjectUtils::build_common_struct_member(member_id_vs_signal_strength_dbm, member_flags_vs_signal_strength_dbm, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_vs_signal_strength_dbm, common_vs_signal_strength_dbm_ec))};
            if (!common_vs_signal_strength_dbm_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure vs_signal_strength_dbm member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_vs_signal_strength_dbm = "vs_signal_strength_dbm";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_vs_signal_strength_dbm;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_vs_signal_strength_dbm = TypeObjectUtils::build_complete_member_detail(name_vs_signal_strength_dbm, member_ann_builtin_vs_signal_strength_dbm, ann_custom_FlatIntelligence);
            CompleteStructMember member_vs_signal_strength_dbm = TypeObjectUtils::build_complete_struct_member(common_vs_signal_strength_dbm, detail_vs_signal_strength_dbm);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_vs_signal_strength_dbm);
        }
        {
            TypeIdentifierPair type_ids_vs_system_error;
            ReturnCode_t return_code_vs_system_error {eprosima::fastdds::dds::RETCODE_OK};
            return_code_vs_system_error =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_vs_system_error);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_vs_system_error)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "vs_system_error Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_vs_system_error = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_vs_system_error = 0x00000003;
            bool common_vs_system_error_ec {false};
            CommonStructMember common_vs_system_error {TypeObjectUtils::build_common_struct_member(member_id_vs_system_error, member_flags_vs_system_error, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_vs_system_error, common_vs_system_error_ec))};
            if (!common_vs_system_error_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure vs_system_error member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_vs_system_error = "vs_system_error";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_vs_system_error;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_vs_system_error = TypeObjectUtils::build_complete_member_detail(name_vs_system_error, member_ann_builtin_vs_system_error, ann_custom_FlatIntelligence);
            CompleteStructMember member_vs_system_error = TypeObjectUtils::build_complete_struct_member(common_vs_system_error, detail_vs_system_error);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_vs_system_error);
        }
        {
            TypeIdentifierPair type_ids_td_target_ID;
            ReturnCode_t return_code_td_target_ID {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_target_ID =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_td_target_ID);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_target_ID)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_td_target_ID))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_td_target_ID = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_target_ID = 0x00000004;
            bool common_td_target_ID_ec {false};
            CommonStructMember common_td_target_ID {TypeObjectUtils::build_common_struct_member(member_id_td_target_ID, member_flags_td_target_ID, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_target_ID, common_td_target_ID_ec))};
            if (!common_td_target_ID_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_target_ID member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_target_ID = "td_target_ID";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_target_ID;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_target_ID = TypeObjectUtils::build_complete_member_detail(name_td_target_ID, member_ann_builtin_td_target_ID, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_target_ID = TypeObjectUtils::build_complete_struct_member(common_td_target_ID, detail_td_target_ID);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_target_ID);
        }
        {
            TypeIdentifierPair type_ids_td_target_type;
            ReturnCode_t return_code_td_target_type {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_target_type =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int16_t", type_ids_td_target_type);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_target_type)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_target_type Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_target_type = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_target_type = 0x00000005;
            bool common_td_target_type_ec {false};
            CommonStructMember common_td_target_type {TypeObjectUtils::build_common_struct_member(member_id_td_target_type, member_flags_td_target_type, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_target_type, common_td_target_type_ec))};
            if (!common_td_target_type_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_target_type member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_target_type = "td_target_type";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_target_type;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_target_type = TypeObjectUtils::build_complete_member_detail(name_td_target_type, member_ann_builtin_td_target_type, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_target_type = TypeObjectUtils::build_complete_struct_member(common_td_target_type, detail_td_target_type);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_target_type);
        }
        {
            TypeIdentifierPair type_ids_td_location_latitude;
            ReturnCode_t return_code_td_location_latitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_location_latitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_td_location_latitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_location_latitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_location_latitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_location_latitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_location_latitude = 0x00000006;
            bool common_td_location_latitude_ec {false};
            CommonStructMember common_td_location_latitude {TypeObjectUtils::build_common_struct_member(member_id_td_location_latitude, member_flags_td_location_latitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_location_latitude, common_td_location_latitude_ec))};
            if (!common_td_location_latitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_location_latitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_location_latitude = "td_location_latitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_location_latitude;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_location_latitude = TypeObjectUtils::build_complete_member_detail(name_td_location_latitude, member_ann_builtin_td_location_latitude, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_location_latitude = TypeObjectUtils::build_complete_struct_member(common_td_location_latitude, detail_td_location_latitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_location_latitude);
        }
        {
            TypeIdentifierPair type_ids_td_location_longitude;
            ReturnCode_t return_code_td_location_longitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_location_longitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_td_location_longitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_location_longitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_location_longitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_location_longitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_location_longitude = 0x00000007;
            bool common_td_location_longitude_ec {false};
            CommonStructMember common_td_location_longitude {TypeObjectUtils::build_common_struct_member(member_id_td_location_longitude, member_flags_td_location_longitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_location_longitude, common_td_location_longitude_ec))};
            if (!common_td_location_longitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_location_longitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_location_longitude = "td_location_longitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_location_longitude;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_location_longitude = TypeObjectUtils::build_complete_member_detail(name_td_location_longitude, member_ann_builtin_td_location_longitude, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_location_longitude = TypeObjectUtils::build_complete_struct_member(common_td_location_longitude, detail_td_location_longitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_location_longitude);
        }
        {
            TypeIdentifierPair type_ids_td_location_altitude;
            ReturnCode_t return_code_td_location_altitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_location_altitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_td_location_altitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_location_altitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_location_altitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_location_altitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_location_altitude = 0x00000008;
            bool common_td_location_altitude_ec {false};
            CommonStructMember common_td_location_altitude {TypeObjectUtils::build_common_struct_member(member_id_td_location_altitude, member_flags_td_location_altitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_location_altitude, common_td_location_altitude_ec))};
            if (!common_td_location_altitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_location_altitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_location_altitude = "td_location_altitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_location_altitude;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_location_altitude = TypeObjectUtils::build_complete_member_detail(name_td_location_altitude, member_ann_builtin_td_location_altitude, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_location_altitude = TypeObjectUtils::build_complete_struct_member(common_td_location_altitude, detail_td_location_altitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_location_altitude);
        }
        {
            TypeIdentifierPair type_ids_td_location_time_seconds;
            ReturnCode_t return_code_td_location_time_seconds {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_location_time_seconds =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_td_location_time_seconds);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_location_time_seconds)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_location_time_seconds Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_location_time_seconds = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_location_time_seconds = 0x00000009;
            bool common_td_location_time_seconds_ec {false};
            CommonStructMember common_td_location_time_seconds {TypeObjectUtils::build_common_struct_member(member_id_td_location_time_seconds, member_flags_td_location_time_seconds, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_location_time_seconds, common_td_location_time_seconds_ec))};
            if (!common_td_location_time_seconds_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_location_time_seconds member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_location_time_seconds = "td_location_time_seconds";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_location_time_seconds;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_location_time_seconds = TypeObjectUtils::build_complete_member_detail(name_td_location_time_seconds, member_ann_builtin_td_location_time_seconds, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_location_time_seconds = TypeObjectUtils::build_complete_struct_member(common_td_location_time_seconds, detail_td_location_time_seconds);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_location_time_seconds);
        }
        {
            TypeIdentifierPair type_ids_td_location_time_nano_seconds;
            ReturnCode_t return_code_td_location_time_nano_seconds {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_location_time_nano_seconds =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_td_location_time_nano_seconds);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_location_time_nano_seconds)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_location_time_nano_seconds Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_location_time_nano_seconds = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_location_time_nano_seconds = 0x0000000a;
            bool common_td_location_time_nano_seconds_ec {false};
            CommonStructMember common_td_location_time_nano_seconds {TypeObjectUtils::build_common_struct_member(member_id_td_location_time_nano_seconds, member_flags_td_location_time_nano_seconds, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_location_time_nano_seconds, common_td_location_time_nano_seconds_ec))};
            if (!common_td_location_time_nano_seconds_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_location_time_nano_seconds member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_location_time_nano_seconds = "td_location_time_nano_seconds";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_location_time_nano_seconds;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_location_time_nano_seconds = TypeObjectUtils::build_complete_member_detail(name_td_location_time_nano_seconds, member_ann_builtin_td_location_time_nano_seconds, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_location_time_nano_seconds = TypeObjectUtils::build_complete_struct_member(common_td_location_time_nano_seconds, detail_td_location_time_nano_seconds);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_location_time_nano_seconds);
        }
        {
            TypeIdentifierPair type_ids_td_location_speed_mps;
            ReturnCode_t return_code_td_location_speed_mps {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_location_speed_mps =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_td_location_speed_mps);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_location_speed_mps)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_location_speed_mps Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_location_speed_mps = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_location_speed_mps = 0x0000000b;
            bool common_td_location_speed_mps_ec {false};
            CommonStructMember common_td_location_speed_mps {TypeObjectUtils::build_common_struct_member(member_id_td_location_speed_mps, member_flags_td_location_speed_mps, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_location_speed_mps, common_td_location_speed_mps_ec))};
            if (!common_td_location_speed_mps_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_location_speed_mps member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_location_speed_mps = "td_location_speed_mps";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_location_speed_mps;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_location_speed_mps = TypeObjectUtils::build_complete_member_detail(name_td_location_speed_mps, member_ann_builtin_td_location_speed_mps, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_location_speed_mps = TypeObjectUtils::build_complete_struct_member(common_td_location_speed_mps, detail_td_location_speed_mps);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_location_speed_mps);
        }
        {
            TypeIdentifierPair type_ids_td_location_orientation_degrees;
            ReturnCode_t return_code_td_location_orientation_degrees {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_location_orientation_degrees =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int16_t", type_ids_td_location_orientation_degrees);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_location_orientation_degrees)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_location_orientation_degrees Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_location_orientation_degrees = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_location_orientation_degrees = 0x0000000c;
            bool common_td_location_orientation_degrees_ec {false};
            CommonStructMember common_td_location_orientation_degrees {TypeObjectUtils::build_common_struct_member(member_id_td_location_orientation_degrees, member_flags_td_location_orientation_degrees, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_location_orientation_degrees, common_td_location_orientation_degrees_ec))};
            if (!common_td_location_orientation_degrees_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_location_orientation_degrees member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_location_orientation_degrees = "td_location_orientation_degrees";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_location_orientation_degrees;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_location_orientation_degrees = TypeObjectUtils::build_complete_member_detail(name_td_location_orientation_degrees, member_ann_builtin_td_location_orientation_degrees, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_location_orientation_degrees = TypeObjectUtils::build_complete_struct_member(common_td_location_orientation_degrees, detail_td_location_orientation_degrees);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_location_orientation_degrees);
        }
        {
            TypeIdentifierPair type_ids_td_confidence_level;
            ReturnCode_t return_code_td_confidence_level {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_confidence_level =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_td_confidence_level);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_confidence_level)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "td_confidence_level Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_td_confidence_level = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_confidence_level = 0x0000000d;
            bool common_td_confidence_level_ec {false};
            CommonStructMember common_td_confidence_level {TypeObjectUtils::build_common_struct_member(member_id_td_confidence_level, member_flags_td_confidence_level, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_confidence_level, common_td_confidence_level_ec))};
            if (!common_td_confidence_level_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_confidence_level member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_confidence_level = "td_confidence_level";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_confidence_level;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_confidence_level = TypeObjectUtils::build_complete_member_detail(name_td_confidence_level, member_ann_builtin_td_confidence_level, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_confidence_level = TypeObjectUtils::build_complete_struct_member(common_td_confidence_level, detail_td_confidence_level);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_confidence_level);
        }
        {
            TypeIdentifierPair type_ids_td_description;
            ReturnCode_t return_code_td_description {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_description =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_td_description);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_description)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_td_description))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_td_description = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_description = 0x0000000e;
            bool common_td_description_ec {false};
            CommonStructMember common_td_description {TypeObjectUtils::build_common_struct_member(member_id_td_description, member_flags_td_description, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_description, common_td_description_ec))};
            if (!common_td_description_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_description member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_description = "td_description";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_description;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_description = TypeObjectUtils::build_complete_member_detail(name_td_description, member_ann_builtin_td_description, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_description = TypeObjectUtils::build_complete_struct_member(common_td_description, detail_td_description);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_description);
        }
        {
            TypeIdentifierPair type_ids_td_raw_data_link;
            ReturnCode_t return_code_td_raw_data_link {eprosima::fastdds::dds::RETCODE_OK};
            return_code_td_raw_data_link =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_td_raw_data_link);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_td_raw_data_link)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_td_raw_data_link))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_td_raw_data_link = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_td_raw_data_link = 0x0000000f;
            bool common_td_raw_data_link_ec {false};
            CommonStructMember common_td_raw_data_link {TypeObjectUtils::build_common_struct_member(member_id_td_raw_data_link, member_flags_td_raw_data_link, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_td_raw_data_link, common_td_raw_data_link_ec))};
            if (!common_td_raw_data_link_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure td_raw_data_link member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_td_raw_data_link = "td_raw_data_link";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_td_raw_data_link;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_td_raw_data_link = TypeObjectUtils::build_complete_member_detail(name_td_raw_data_link, member_ann_builtin_td_raw_data_link, ann_custom_FlatIntelligence);
            CompleteStructMember member_td_raw_data_link = TypeObjectUtils::build_complete_struct_member(common_td_raw_data_link, detail_td_raw_data_link);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_td_raw_data_link);
        }
        {
            TypeIdentifierPair type_ids_ta_command;
            ReturnCode_t return_code_ta_command {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ta_command =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_ta_command);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ta_command)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_ta_command))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_ta_command = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ta_command = 0x00000010;
            bool common_ta_command_ec {false};
            CommonStructMember common_ta_command {TypeObjectUtils::build_common_struct_member(member_id_ta_command, member_flags_ta_command, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ta_command, common_ta_command_ec))};
            if (!common_ta_command_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ta_command member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ta_command = "ta_command";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ta_command;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_ta_command = TypeObjectUtils::build_complete_member_detail(name_ta_command, member_ann_builtin_ta_command, ann_custom_FlatIntelligence);
            CompleteStructMember member_ta_command = TypeObjectUtils::build_complete_struct_member(common_ta_command, detail_ta_command);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_ta_command);
        }
        {
            TypeIdentifierPair type_ids_ta_location_latitude;
            ReturnCode_t return_code_ta_location_latitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ta_location_latitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_ta_location_latitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ta_location_latitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ta_location_latitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ta_location_latitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ta_location_latitude = 0x00000011;
            bool common_ta_location_latitude_ec {false};
            CommonStructMember common_ta_location_latitude {TypeObjectUtils::build_common_struct_member(member_id_ta_location_latitude, member_flags_ta_location_latitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ta_location_latitude, common_ta_location_latitude_ec))};
            if (!common_ta_location_latitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ta_location_latitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ta_location_latitude = "ta_location_latitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ta_location_latitude;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_ta_location_latitude = TypeObjectUtils::build_complete_member_detail(name_ta_location_latitude, member_ann_builtin_ta_location_latitude, ann_custom_FlatIntelligence);
            CompleteStructMember member_ta_location_latitude = TypeObjectUtils::build_complete_struct_member(common_ta_location_latitude, detail_ta_location_latitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_ta_location_latitude);
        }
        {
            TypeIdentifierPair type_ids_ta_location_longitude;
            ReturnCode_t return_code_ta_location_longitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ta_location_longitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_ta_location_longitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ta_location_longitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ta_location_longitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ta_location_longitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ta_location_longitude = 0x00000012;
            bool common_ta_location_longitude_ec {false};
            CommonStructMember common_ta_location_longitude {TypeObjectUtils::build_common_struct_member(member_id_ta_location_longitude, member_flags_ta_location_longitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ta_location_longitude, common_ta_location_longitude_ec))};
            if (!common_ta_location_longitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ta_location_longitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ta_location_longitude = "ta_location_longitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ta_location_longitude;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_ta_location_longitude = TypeObjectUtils::build_complete_member_detail(name_ta_location_longitude, member_ann_builtin_ta_location_longitude, ann_custom_FlatIntelligence);
            CompleteStructMember member_ta_location_longitude = TypeObjectUtils::build_complete_struct_member(common_ta_location_longitude, detail_ta_location_longitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_ta_location_longitude);
        }
        {
            TypeIdentifierPair type_ids_ta_location_altitude;
            ReturnCode_t return_code_ta_location_altitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ta_location_altitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_ta_location_altitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ta_location_altitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ta_location_altitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ta_location_altitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ta_location_altitude = 0x00000013;
            bool common_ta_location_altitude_ec {false};
            CommonStructMember common_ta_location_altitude {TypeObjectUtils::build_common_struct_member(member_id_ta_location_altitude, member_flags_ta_location_altitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ta_location_altitude, common_ta_location_altitude_ec))};
            if (!common_ta_location_altitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ta_location_altitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ta_location_altitude = "ta_location_altitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ta_location_altitude;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_ta_location_altitude = TypeObjectUtils::build_complete_member_detail(name_ta_location_altitude, member_ann_builtin_ta_location_altitude, ann_custom_FlatIntelligence);
            CompleteStructMember member_ta_location_altitude = TypeObjectUtils::build_complete_struct_member(common_ta_location_altitude, detail_ta_location_altitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_ta_location_altitude);
        }
        {
            TypeIdentifierPair type_ids_ta_location_time_seconds;
            ReturnCode_t return_code_ta_location_time_seconds {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ta_location_time_seconds =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_ta_location_time_seconds);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ta_location_time_seconds)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ta_location_time_seconds Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ta_location_time_seconds = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ta_location_time_seconds = 0x00000014;
            bool common_ta_location_time_seconds_ec {false};
            CommonStructMember common_ta_location_time_seconds {TypeObjectUtils::build_common_struct_member(member_id_ta_location_time_seconds, member_flags_ta_location_time_seconds, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ta_location_time_seconds, common_ta_location_time_seconds_ec))};
            if (!common_ta_location_time_seconds_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ta_location_time_seconds member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ta_location_time_seconds = "ta_location_time_seconds";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ta_location_time_seconds;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_ta_location_time_seconds = TypeObjectUtils::build_complete_member_detail(name_ta_location_time_seconds, member_ann_builtin_ta_location_time_seconds, ann_custom_FlatIntelligence);
            CompleteStructMember member_ta_location_time_seconds = TypeObjectUtils::build_complete_struct_member(common_ta_location_time_seconds, detail_ta_location_time_seconds);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_ta_location_time_seconds);
        }
        {
            TypeIdentifierPair type_ids_ta_location_time_nano_seconds;
            ReturnCode_t return_code_ta_location_time_nano_seconds {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ta_location_time_nano_seconds =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_ta_location_time_nano_seconds);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ta_location_time_nano_seconds)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ta_location_time_nano_seconds Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ta_location_time_nano_seconds = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ta_location_time_nano_seconds = 0x00000015;
            bool common_ta_location_time_nano_seconds_ec {false};
            CommonStructMember common_ta_location_time_nano_seconds {TypeObjectUtils::build_common_struct_member(member_id_ta_location_time_nano_seconds, member_flags_ta_location_time_nano_seconds, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ta_location_time_nano_seconds, common_ta_location_time_nano_seconds_ec))};
            if (!common_ta_location_time_nano_seconds_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ta_location_time_nano_seconds member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ta_location_time_nano_seconds = "ta_location_time_nano_seconds";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ta_location_time_nano_seconds;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_ta_location_time_nano_seconds = TypeObjectUtils::build_complete_member_detail(name_ta_location_time_nano_seconds, member_ann_builtin_ta_location_time_nano_seconds, ann_custom_FlatIntelligence);
            CompleteStructMember member_ta_location_time_nano_seconds = TypeObjectUtils::build_complete_struct_member(common_ta_location_time_nano_seconds, detail_ta_location_time_nano_seconds);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_ta_location_time_nano_seconds);
        }
        {
            TypeIdentifierPair type_ids_ta_location_speed_mps;
            ReturnCode_t return_code_ta_location_speed_mps {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ta_location_speed_mps =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_ta_location_speed_mps);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ta_location_speed_mps)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ta_location_speed_mps Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ta_location_speed_mps = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ta_location_speed_mps = 0x00000016;
            bool common_ta_location_speed_mps_ec {false};
            CommonStructMember common_ta_location_speed_mps {TypeObjectUtils::build_common_struct_member(member_id_ta_location_speed_mps, member_flags_ta_location_speed_mps, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ta_location_speed_mps, common_ta_location_speed_mps_ec))};
            if (!common_ta_location_speed_mps_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ta_location_speed_mps member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ta_location_speed_mps = "ta_location_speed_mps";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ta_location_speed_mps;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_ta_location_speed_mps = TypeObjectUtils::build_complete_member_detail(name_ta_location_speed_mps, member_ann_builtin_ta_location_speed_mps, ann_custom_FlatIntelligence);
            CompleteStructMember member_ta_location_speed_mps = TypeObjectUtils::build_complete_struct_member(common_ta_location_speed_mps, detail_ta_location_speed_mps);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_ta_location_speed_mps);
        }
        {
            TypeIdentifierPair type_ids_ta_location_orientation_degrees;
            ReturnCode_t return_code_ta_location_orientation_degrees {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ta_location_orientation_degrees =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int16_t", type_ids_ta_location_orientation_degrees);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ta_location_orientation_degrees)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ta_location_orientation_degrees Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ta_location_orientation_degrees = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ta_location_orientation_degrees = 0x00000017;
            bool common_ta_location_orientation_degrees_ec {false};
            CommonStructMember common_ta_location_orientation_degrees {TypeObjectUtils::build_common_struct_member(member_id_ta_location_orientation_degrees, member_flags_ta_location_orientation_degrees, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ta_location_orientation_degrees, common_ta_location_orientation_degrees_ec))};
            if (!common_ta_location_orientation_degrees_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ta_location_orientation_degrees member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ta_location_orientation_degrees = "ta_location_orientation_degrees";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ta_location_orientation_degrees;
            ann_custom_FlatIntelligence.reset();
            CompleteMemberDetail detail_ta_location_orientation_degrees = TypeObjectUtils::build_complete_member_detail(name_ta_location_orientation_degrees, member_ann_builtin_ta_location_orientation_degrees, ann_custom_FlatIntelligence);
            CompleteStructMember member_ta_location_orientation_degrees = TypeObjectUtils::build_complete_struct_member(common_ta_location_orientation_degrees, detail_ta_location_orientation_degrees);
            TypeObjectUtils::add_complete_struct_member(member_seq_FlatIntelligence, member_ta_location_orientation_degrees);
        }
        CompleteStructType struct_type_FlatIntelligence = TypeObjectUtils::build_complete_struct_type(struct_flags_FlatIntelligence, header_FlatIntelligence, member_seq_FlatIntelligence);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_FlatIntelligence, type_name_FlatIntelligence.to_string(), type_ids_FlatIntelligence))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Intelligence::FlatIntelligence already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace Intelligence

